"""Auto-generated module exports."""

from .BranchComparer import BranchComparer
from .BranchComparison import BranchComparison
from .CodeGenerator import CodeGenerator
from .ConflictResolution import ConflictResolution
from .ContextAgent import ContextAgent, DEFAULT_TEMPLATES, DEFAULT_VALIDATION_RULES
from .ContextAnnotation import ContextAnnotation
from .ContextDiff import ContextDiff
from .ContextDiffer import ContextDiffer
from .ContextExporter import ContextExporter
from .ContextInheritance import ContextInheritance
from .ContextPriority import ContextPriority
from .ContextRecommendation import ContextRecommendation
from .ContextRecommender import ContextRecommender
from .ContextSharingManager import ContextSharingManager
from .ContextTag import ContextTag
from .ContextTemplate import ContextTemplate
from .ContextVersion import ContextVersion
from .ContextVisualizer import ContextVisualizer
from .CrossRepoAnalyzer import CrossRepoAnalyzer
from .CrossRepoContext import CrossRepoContext
from .ExportFormat import ExportFormat
from .ExportedContext import ExportedContext
from .FileCategory import FileCategory
from .GeneratedCode import GeneratedCode
from .InheritanceMode import InheritanceMode
from .InheritedContext import InheritedContext
from .KnowledgeAgent import KnowledgeAgent
from .MergeConflict import MergeConflict
from .MergeConflictResolver import MergeConflictResolver
from .NLQueryEngine import NLQueryEngine
from .NLQueryResult import NLQueryResult
from .RefactoringAdvisor import RefactoringAdvisor
from .RefactoringSuggestion import RefactoringSuggestion
from .SearchAlgorithm import SearchAlgorithm
from .SemanticSearchEngine import SemanticSearchEngine
from .SemanticSearchResult import SemanticSearchResult
from .SharedContext import SharedContext
from .SharingPermission import SharingPermission
from .ValidationRule import ValidationRule
from .VisualizationData import VisualizationData
from .VisualizationType import VisualizationType
