#!/usr/bin/env python3
"""
LLM_CONTEXT_START

## Source: src-old/logic/agents/cognitive/context_tagging_mixin.description.md

# Description: src/logic/agents/cognitive/context_tagging_mixin.py

Module docstring (if present):

    Mixin for context tagging capabilities.

Top-level members:
- Classes: ContextTaggingMixin

Notes:
- This description was auto-generated by scripts/generate_docs_for_src.py
## Source: src-old/logic/agents/cognitive/context_tagging_mixin.improvements.md

# Improvements: src/logic/agents/cognitive/context_tagging_mixin.py

Suggested improvements (automatically generated):
- Add unit tests covering core behavior and edge cases.
- Break large modules into smaller, testable components.
- Avoid heavy imports at module import time; import lazily where appropriate.
- Add type hints and explicit return types for public functions.
- Add logging and better error handling for file and IO operations.
- Consider dependency injection for filesystem and environment interactions.

LLM_CONTEXT_END
"""

from __future__ import annotations
# Copyright 2026 PyAgent Authors
# Licensed under the Apache License, Version 2.0 (the "License");


"""Mixin for context tagging capabilities."""

from src.logic.agents.cognitive.context.models.context_tag import ContextTag


class ContextTaggingMixin:
    """Tagging methods for ContextAgent."""

    def add_tag(self, tag: ContextTag) -> None:
        """Add a tag."""
        if not hasattr(self, "_tags"):
            self._tags: dict[str, ContextTag] = {}
        self._tags[tag.name] = tag

    def remove_tag(self, tag_name: str) -> bool:
        """Remove a tag."""
        if hasattr(self, "_tags") and tag_name in self._tags:
            del self._tags[tag_name]
            return True
        return False

    def get_tags(self) -> list[ContextTag]:
        """Get all tags."""
        return list(getattr(self, "_tags", {}).values())

    def has_tag(self, tag_name: str) -> bool:
        """Check if a tag exists."""
        return tag_name in getattr(self, "_tags", {})

    def get_tags_by_parent(self, parent_name: str) -> list[ContextTag]:
        """Get all tags with a specific parent."""
        return [t for t in getattr(self, "_tags", {}).values() if t.parent == parent_name]
