#!/usr/bin/env python3
"""
LLM_CONTEXT_START

## Source: src-old/logic/agents/cognitive/context_annotation_mixin.description.md

# Description: src/logic/agents/cognitive/context_annotation_mixin.py

Module docstring (if present):

    Mixin for context annotation capabilities.

Top-level members:
- Classes: ContextAnnotationMixin

Notes:
- This description was auto-generated by scripts/generate_docs_for_src.py
## Source: src-old/logic/agents/cognitive/context_annotation_mixin.improvements.md

# Improvements: src/logic/agents/cognitive/context_annotation_mixin.py

Suggested improvements (automatically generated):
- Add unit tests covering core behavior and edge cases.
- Break large modules into smaller, testable components.
- Avoid heavy imports at module import time; import lazily where appropriate.
- Add type hints and explicit return types for public functions.
- Add logging and better error handling for file and IO operations.
- Consider dependency injection for filesystem and environment interactions.

LLM_CONTEXT_END
"""

from __future__ import annotations

# Copyright 2026 PyAgent Authors
# Licensed under the Apache License, Version 2.0 (the "License");


"""Mixin for context annotation capabilities."""

import hashlib
from datetime import datetime
from src.logic.agents.cognitive.context.models.context_annotation import (
    ContextAnnotation,
)


class ContextAnnotationMixin:
    """Annotation methods for ContextAgent."""

    def add_annotation(
        self, line_number: int, content: str, author: str = ""
    ) -> ContextAnnotation:
        """Add an annotation to the context."""
        annotation = ContextAnnotation(
            id=hashlib.md5(f"{line_number}:{content}".encode()).hexdigest()[:8],
            line_number=line_number,
            content=content,
            author=author,
            timestamp=datetime.now().isoformat(),
        )
        if not hasattr(self, "_annotations"):
            self._annotations: list[ContextAnnotation] = []
        self._annotations.append(annotation)
        return annotation

    def get_annotations(self) -> list[ContextAnnotation]:
        """Get all annotations."""
        return getattr(self, "_annotations", [])

    def get_annotations_for_line(self, line_number: int) -> list[ContextAnnotation]:
        """Get annotations for a specific line."""
        return [
            a for a in getattr(self, "_annotations", []) if a.line_number == line_number
        ]

    def resolve_annotation(self, annotation_id: str) -> bool:
        """Mark an annotation as resolved."""
        for annotation in getattr(self, "_annotations", []):
            if annotation.id == annotation_id:
                annotation.resolved = True
                return True
        return False

    def remove_annotation(self, annotation_id: str) -> bool:
        """Remove an annotation."""
        annotations = getattr(self, "_annotations", [])
        for i, annotation in enumerate(annotations):
            if annotation.id == annotation_id:
                del annotations[i]
                return True
        return False
