#!/usr/bin/env python3
# Copyright 2026 PyAgent Authors
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


"""LLM_CONTEXT_START

## Source: src-old/logic/agents/cognitive/hierarchical_memory_agent.description.md

# Description: src/logic/agents/cognitive/hierarchical_memory_agent.py

Module docstring (if present):

    Agent specializing in Multi-Resolution Hierarchical Memory.
    Manages Short-term (Episodic), Mid-term (Working), Long-term (Semantic), and Archival storage tiers.

Top-level members:
- Classes: HierarchicalMemoryAgent

Notes:
- This description was auto-generated by scripts/generate_docs_for_src.py
## Source: src-old/logic/agents/cognitive/hierarchical_memory_agent.improvements.md

# Improvements: src/logic/agents/cognitive/hierarchical_memory_agent.py

Suggested improvements (automatically generated):
- Add unit tests covering core behavior and edge cases.
- Break large modules into smaller, testable components.
- Avoid heavy imports at module import time; import lazily where appropriate.
- Add type hints and explicit return types for public functions.
- Add logging and better error handling for file and IO operations.
- Consider dependency injection for filesystem and environment interactions.

LLM_CONTEXT_END

"""

"""Agent specializing in Multi-Resolution Hierarchical Memory.
Manages Short-term (Episodic), Mid-term (Working), Long-term (Semantic), and Archival storage tiers.
"""
from pathlib import Path

from src.core.base.lifecycle.base_agent import BaseAgent
from src.core.base.lifecycle.version import VERSION

from .mixins.memory_query_mixin import MemoryQueryMixin
from .mixins.memory_storage_mixin import MemoryStorageMixin

__version__ = VERSION


# pylint: disable=too-many-ancestors
class HierarchicalMemoryAgent(BaseAgent, MemoryStorageMixin, MemoryQueryMixin):
    """
    """
