#!/usr/bin/env python3
"""LLM_CONTEXT_START

## Source: src-old/logic/strategies/agent_strategy.description.md

# Description: src/logic/strategies/agent_strategy.py

Module docstring (if present):

    Auto-extracted class from agent_strategies.py

Top-level members:
- Classes: AgentStrategy

Notes:
- This description was auto-generated by scripts/generate_docs_for_src.py
## Source: src-old/logic/strategies/agent_strategy.improvements.md

# Improvements: src/logic/strategies/agent_strategy.py

Suggested improvements (automatically generated):
- Add unit tests covering core behavior and edge cases.
- Break large modules into smaller, testable components.
- Avoid heavy imports at module import time; import lazily where appropriate.
- Add type hints and explicit return types for public functions.
- Add logging and better error handling for file and IO operations.
- Consider dependency injection for filesystem and environment interactions.

LLM_CONTEXT_END

"""

from __future__ import annotations

# Copyright 2026 PyAgent Authors
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
from collections.abc import Callable

"""Auto-extracted class from agent_strategies.py"""


from abc import ABC, abstractmethod

from src.core.base.lifecycle.version import VERSION

BackendFunction = Callable[[str, str | None, list[dict[str, str]] | None], str]

__version__ = VERSION


class AgentStrategy(ABC):
    """Abstract base class for agent execution strategies."""

    @abstractmethod
    async def execute(
        self,
        prompt: str,
        context: str,
        backend_call: BackendFunction,
        system_prompt: str | None = None,
        history: list[dict[str, str]] | None = None,
        agent_name: str = "UnknownAgent",
        task_id: str = "UnknownTask",
    ) -> str:
        """Execute the strategy to generate a response.

        Args:
            prompt: The user's request or instruction.
            context: The current file content or context.
            backend_call: A callable to invoke the LLM.
            system_prompt: Optional system prompt.
            history: Optional conversation history.
            agent_name: The name of the agent executing the strategy.
            task_id: A unique identifier for the current task.

        Returns:
            The final generated content.

        """
        ...
