#!/usr/bin/env python3
"""
LLM_CONTEXT_START

## Source: src-old/logic/strategies/plan_executor.description.md

# Description: src/logic/strategies/plan_executor.py

Module docstring (if present):

    Strategies Module: Unified interface for agent decision-making strategies.

Top-level members:
- (no top-level classes or functions)

Notes:
- This description was auto-generated by scripts/generate_docs_for_src.py
## Source: src-old/logic/strategies/plan_executor.improvements.md

# Improvements: src/logic/strategies/plan_executor.py

Suggested improvements (automatically generated):
- Add unit tests covering core behavior and edge cases.
- Break large modules into smaller, testable components.
- Avoid heavy imports at module import time; import lazily where appropriate.
- Add type hints and explicit return types for public functions.
- Add logging and better error handling for file and IO operations.
- Consider dependency injection for filesystem and environment interactions.

LLM_CONTEXT_END
"""

from __future__ import annotations
# Copyright 2026 PyAgent Authors
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


"""
Strategies Module: Unified interface for agent decision-making strategies.
"""


import sys
from collections.abc import Awaitable, Callable
from pathlib import Path

from src.core.base.lifecycle.version import VERSION

# Ensure project root and src are in path for modular imports
root = Path(__file__).parent.parent
if str(root) not in sys.path:
    sys.path.append(str(root))
if str(root / "src") not in sys.path:
    sys.path.append(str(root / "src"))

# Modular imports
__version__ = VERSION

# Type alias for functional compatibility
BackendFunction = Callable[[str, str | None, list[dict[str, str]] | None], Awaitable[str]]
