#!/usr/bin/env python3
"""
LLM_CONTEXT_START

## Source: src-old/logic/strategies/reflexion_strategy.description.md

# Description: src/logic/strategies/reflexion_strategy.py

Module docstring (if present):

    Reflexion strategy.py module.

Top-level members:
- Classes: ReflexionStrategy

Notes:
- This description was auto-generated by scripts/generate_docs_for_src.py
## Source: src-old/logic/strategies/reflexion_strategy.improvements.md

# Improvements: src/logic/strategies/reflexion_strategy.py

Suggested improvements (automatically generated):
- Add unit tests covering core behavior and edge cases.
- Break large modules into smaller, testable components.
- Avoid heavy imports at module import time; import lazily where appropriate.
- Add type hints and explicit return types for public functions.
- Add logging and better error handling for file and IO operations.
- Consider dependency injection for filesystem and environment interactions.

LLM_CONTEXT_END
"""

from __future__ import annotations

"""
Reflexion strategy.py module.
"""
# Copyright 2026 PyAgent Authors
# Apache 2.0 License


import logging
from collections.abc import Callable
from typing import TYPE_CHECKING, Dict, List, Optional

from src.core.base.lifecycle.version import VERSION

from .agent_strategy import AgentStrategy

BackendFunction = Callable[[str, str | None, list[dict[str, str]] | None], str]
__version__ = VERSION

class ReflexionStrategy(AgentStrategy):
    """Reflexion strategy: Draft -> Critique -> Revise."""
    async def _safe_backend_call(
        self,
        step_name: str,
        call_prompt: str,
        backend_call: BackendFunction,
        system_prompt: str | None,
        history: list[dict[str, str]] | None,
        original_prompt_for_logging: str,
    ) -> str:
        """
        Helper method to encapsulate backend calls with error handling and logging.
        """
        try:
            response = await backend_call(call_prompt, system_prompt, history)
            logging.info(f"Reflexion {step_name.capitalize()}:\n{response}")
            return response
        except Exception as e:
            logging.error(
                f"Failed during {step_name} step for prompt: {original_prompt_for_logging[:100]}... Error: {e}"
            )
            raise  # Re-raise or handle more gracefully based on desired behavior

    async def execute(
        self,
        prompt: str,
        context: str,
        backend_call: BackendFunction,
        system_prompt: str | None = None,
        history: list[dict[str, str]] | None = None,
        agent_name: str = "UnknownAgent",
        task_id: str = "UnknownTask",
    ) -> str:
        # Step 1: Draft
        draft_prompt = f"{prompt}\n\nContext:\n{context}"
        draft = await self._safe_backend_call(
            "draft",
            draft_prompt,
            backend_call,
            system_prompt,
            history,
            prompt,
            agent_name,
            task_id,
        )

        # Step 2: Critique
        critique_prompt = (
            f"Original Request: {prompt}\n\n"
            f"Draft Implementation:\n{draft}\n\n"
            "Critique this implementation. Identify any bugs, missing requirements, "
            "or style issues. Be harsh but constructive."
        )
        critique = await self._safe_backend_call(
            "critique",
            critique_prompt,
            backend_call,
            "You are a senior code reviewer.",
            [],
            prompt,
            agent_name,
            task_id,
        )

        # Step 3: Revise
        revision_prompt = (
            f"Original Request: {prompt}\n\n"
            f"Draft Implementation:\n{draft}\n\n"
            f"Critique:\n{critique}\n\n"
            "Please rewrite the implementation to address the critique. "
            "Output ONLY the final code/content."
        )
        # We append the critique to the history for the revision step
        new_history = list(history) if history else []
        new_history.append({"role": "assistant", "content": critique})

        return await self._safe_backend_call(
            "revise",
            revision_prompt,
            backend_call,
            system_prompt,
            new_history,
            prompt,
            agent_name,
            task_id,
        )
