# -*- coding: utf-8 -*-
"""Extracted test classes from test_agent_context.py."""

__all__ = [
    "TestAPIDocumentationExtraction",
    "TestASTSignatureExtraction",
    "TestArchitectureDecisions",
    "TestChangeStatistics",
    "TestCodeMetrics",
    "TestCodeSmellDetection",
    "TestContextAccessControl",
    "TestContextAnnotation",
    "TestContextArchival",
    "TestContextAwareCodeGeneration",
    "TestContextBasedRefactoring",
    "TestContextCachingComprehensive",
    "TestContextCachingImprovements",
    "TestContextCompression",
    "TestContextCreation",
    "TestContextDiffing",
    "TestContextExport",
    "TestContextFiltering",
    "TestContextInheritance",
    "TestContextInheritanceComprehensive",
    "TestContextIntegration",
    "TestContextLifecycle",
    "TestContextMergeConflict",
    "TestContextMerging",
    "TestContextNotification",
    "TestContextPrioritization",
    "TestContextPropagation",
    "TestContextRecommendation",
    "TestContextSearchIndexing",
    "TestContextSerialization",
    "TestContextStateTracking",
    "TestContextStorage",
    "TestContextSummarization",
    "TestContextTagging",
    "TestContextTemplateApplication",
    "TestContextValidation",
    "TestContextValidationComprehensive",
    "TestContextVariables",
    "TestContextVersioning",
    "TestContextVisualization",
    "TestCoverageMetrics",
    "TestCrossModuleContext",
    "TestCrossRepositoryContext",
    "TestDependencyGraphAnalysis",
    "TestGitHistoryIntegration",
    "TestNaturalLanguageSearch",
    "TestPluginSystem",
    "TestRelatedFilesDetection",
    "TestSemanticSearch",
]

from .core import *  # noqa: F401, F403
from .integration import *  # noqa: F401, F403
from .advanced import *  # noqa: F401, F403
