[pytest]
testpaths = tests
norecursedirs = .git .venv* venv* build dist .idea .tox __pycache__ 
python_files = test_*.py *_test.py
python_classes = Test*
python_functions = test_*
asyncio_mode = strict
#import_mode = importlib
filterwarnings =
    ignore:.*SwigPyPacked.*:DeprecationWarning
    ignore:.*SwigPyObject.*:DeprecationWarning
    ignore:.*swigvarlink.*:DeprecationWarning
    ignore:The module 'cgi' is deprecated:DeprecationWarning
    ignore:the load_module\(\) method is deprecated:DeprecationWarning
    ignore:.*builtin type .* has no __module__ attribute:DeprecationWarning
    ignore::pytest.PytestRemovedIn9Warning
