#!/usr/bin/env python3
# Copyright 2026 PyAgent Authors
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
LLM_CONTEXT_START

## Source: src-old/interface/slash_commands.description.md

# Description: src/interface/slash_commands.py

Module docstring (if present):

    SlashCommands - Chat prompt slash command parser and executor.

    Provides backward compatibility for the moved SlashCommands implementation.
    Moved to src/interface/commands/

Top-level members:
- (no top-level classes or functions)

Notes:
- This description was auto-generated by scripts/generate_docs_for_src.py
## Source: src-old/interface/slash_commands.improvements.md

# Improvements: src/interface/slash_commands.py

Suggested improvements (automatically generated):
- Add unit tests covering core behavior and edge cases.
- Break large modules into smaller, testable components.
- Avoid heavy imports at module import time; import lazily where appropriate.
- Add type hints and explicit return types for public functions.
- Add logging and better error handling for file and IO operations.
- Consider dependency injection for filesystem and environment interactions.

LLM_CONTEXT_END
"""

"""
SlashCommands - Chat prompt slash command parser and executor.

Provides backward compatibility for the moved SlashCommands implementation.
Moved to src/interface/commands/
"""

from .commands import (CommandContext, CommandDefinition, CommandParser,
                       CommandRegistry, CommandResult, ParsedCommand,
                       ProcessedPrompt, SlashCommands, command,
                       execute_command, get_slash_commands, parse_commands,
                       process_prompt, register_command)

__all__ = [
    # Classes
    "SlashCommands",
    "CommandParser",
    "CommandContext",
    "CommandResult",
    "CommandDefinition",
    "CommandRegistry",
    "ParsedCommand",
    "ProcessedPrompt",
    # Functions
    "parse_commands",
    "get_slash_commands",
    "process_prompt",
    "execute_command",
    "register_command",
    "command",
]
