#!/usr/bin/env python3
"""LLM_CONTEXT_START

## Source: src-old/observability/stats/subs_engine.description.md

# Description: src/observability/stats/subs_engine.py

Module docstring (if present):

    Subs engine.py module.

Top-level members:
- Classes: AnnotationManager, StatsAnnotationManager, SubscriptionManager, StatsSubscriptionManager

Notes:
- This description was auto-generated by scripts/generate_docs_for_src.py
## Source: src-old/observability/stats/subs_engine.improvements.md

# Improvements: src/observability/stats/subs_engine.py

Suggested improvements (automatically generated):
- Add unit tests covering core behavior and edge cases.
- Break large modules into smaller, testable components.
- Avoid heavy imports at module import time; import lazily where appropriate.
- Add type hints and explicit return types for public functions.
- Add logging and better error handling for file and IO operations.
- Consider dependency injection for filesystem and environment interactions.

LLM_CONTEXT_END

"""
from __future__ import annotations


"""
Subs engine.py module.
"""
# Copyright 2026 PyAgent Authors
# Subscription and annotation management engine.


import contextlib
import hashlib
import logging
from datetime import datetime
from typing import Any, Callable

from .metrics import MetricAnnotation
from .observability_core import MetricSubscription, StatsSubscription

logger = logging.getLogger(__name__)


class AnnotationManager:
    """
    """
