#!/usr/bin/env python3
# Copyright 2026 PyAgent Authors
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
LLM_CONTEXT_START

## Source: src-old/core/base/common/__init__.description.md

# Description: src/core/base/common/__init__.py

Module docstring (if present):

    Common package.

Top-level members:
- (no top-level classes or functions)

Notes:
- This description was auto-generated by scripts/generate_docs_for_src.py
## Source: src-old/core/base/common/__init__.improvements.md

# Improvements: src/core/base/common/__init__.py

Suggested improvements (automatically generated):
- Add unit tests covering core behavior and edge cases.
- Break large modules into smaller, testable components.
- Avoid heavy imports at module import time; import lazily where appropriate.
- Add type hints and explicit return types for public functions.
- Add logging and better error handling for file and IO operations.
- Consider dependency injection for filesystem and environment interactions.

LLM_CONTEXT_END
"""

"""
Common package.
"""

# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright contributors to the PyAgent project

try:
    from .analysis_core import AnalysisCore  # noqa: F401
except ImportError:
    AnalysisCore = None  # type: ignore
try:
    from .auth_core import AuthCore  # noqa: F401
except ImportError:  # circular dependency during early imports (models need AuthConfig)
    AuthCore = None  # type: ignore
try:
    from .base_core import BaseCore  # noqa: F401
except ImportError:
    BaseCore = None  # type: ignore
try:
    from .batch_core import BatchCore  # noqa: F401
except ImportError:
    BatchCore = None  # type: ignore
try:
    from .cache_core import CacheCore  # noqa: F401
except ImportError:
    CacheCore = None  # type: ignore
try:
    from .connectivity_core import ConnectivityCore  # noqa: F401
except ImportError:
    ConnectivityCore = None  # type: ignore
try:
    from .consensus_core import ConsensusCore  # noqa: F401
except ImportError:
    ConsensusCore = None  # type: ignore
try:
    from .diff_core import DiffCore  # noqa: F401
except ImportError:
    DiffCore = None  # type: ignore
try:
    from .execution_core import ExecutionCore  # noqa: F401
except ImportError:
    ExecutionCore = None  # type: ignore
try:
    from .formula_core import FormulaCore  # noqa: F401
except ImportError:
    FormulaCore = None  # type: ignore
try:
    from .git_core import GitCore  # noqa: F401
except ImportError:
    GitCore = None  # type: ignore
try:
    from .hardware_core import HardwareCore  # noqa: F401
except ImportError:
    HardwareCore = None  # type: ignore
try:
    from .health_core import HealthCore  # noqa: F401
except ImportError:
    HealthCore = None  # type: ignore
try:
    from .inference_core import InferenceCore  # noqa: F401
except ImportError:
    InferenceCore = None  # type: ignore
try:
    from .lock_core import LockCore  # noqa: F401
except ImportError:
    LockCore = None  # type: ignore
try:
    from .multimodal_core import (
        MultimodalCore,
        MultimodalStreamSession,
        StreamingAudioProcessor,
        StreamingVisionEncoder,
        TemporalModalityBuffer,
    )
except ImportError:
    MultimodalCore = None  # type: ignore
    MultimodalStreamSession = None  # type: ignore
    StreamingAudioProcessor = None  # type: ignore
    StreamingVisionEncoder = None  # type: ignore
    TemporalModalityBuffer = None  # type: ignore
try:
    from .registry_core import RegistryCore  # noqa: F401
except ImportError:
    RegistryCore = None  # type: ignore
try:
    from .resource_core import ResourceCore  # noqa: F401
except ImportError:
    ResourceCore = None  # type: ignore
try:
    from .routing_core import RoutingCore  # noqa: F401
except ImportError:
    RoutingCore = None  # type: ignore
try:
    from .scaling_core import ScalingCore  # noqa: F401
except ImportError:
    ScalingCore = None  # type: ignore
try:
    from .search_core import SearchCore  # noqa: F401
except ImportError:
    SearchCore = None  # type: ignore
try:
    from .secret_core import SecretCore  # noqa: F401
except ImportError:
    SecretCore = None  # type: ignore
try:
    from .shard_core import ShardCore  # noqa: F401
except ImportError:
    ShardCore = None  # type: ignore
from .shell_core import ShellCore  # noqa: F401
try:
    from .signal_core import SignalCore  # noqa: F401
except ImportError:
    SignalCore = None  # type: ignore
try:
    from .stability_core import StabilityCore  # noqa: F401
except ImportError:
    StabilityCore = None  # type: ignore
try:
    from .telemetry_core import TelemetryCore  # noqa: F401
except ImportError:
    TelemetryCore = None  # type: ignore
try:
    from .template_core import TemplateCore  # noqa: F401
except ImportError:
    TemplateCore = None  # type: ignore
from .time_core import TimeCore  # noqa: F401
try:
    from .validation_core import ValidationCore  # noqa: F401
except ImportError:
    ValidationCore = None  # type: ignore
try:
    from .workspace_core import WorkspaceCore  # noqa: F401
except ImportError:
    WorkspaceCore = None  # type: ignore

__all__ = [
    "BaseCore",
    "StabilityCore",
    "ConsensusCore",
    "ValidationCore",
    "InferenceCore",
    "ConnectivityCore",
    "AuthCore",
    "TelemetryCore",
    "RoutingCore",
    "SignalCore",
    "SearchCore",
    "ShardCore",
    "WorkspaceCore",
    "AnalysisCore",
    "HealthCore",
    "FormulaCore",
    "DiffCore",
    "GitCore",
    "ScalingCore",
    "SecretCore",
    "ExecutionCore",
    "RegistryCore",
    "CacheCore",
    "BatchCore",
    "LockCore",
    "ResourceCore",
    "TemplateCore",
    "MultimodalCore",
    "StreamingAudioProcessor",
    "TemporalModalityBuffer",
    "StreamingVisionEncoder",
    "MultimodalStreamSession",
    "HardwareCore",
    "ShellCore",
    "TimeCore",
]
