#!/usr/bin/env python3
# Copyright 2026 PyAgent Authors
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
"""LLM_CONTEXT_START

## Source: src-old/core/base/common/base_utilities.description.md

# Description: src/core/base/common/base_utilities.py

Module docstring (if present):

    Utility classes for BaseAgent framework.

Top-level members:
- Functions: strip_ansi_codes, bulk_replace, setup_logging, as_tool, create_main_function

Notes:
- This description was auto-generated by scripts/generate_docs_for_src.py
## Source: src-old/core/base/common/base_utilities.improvements.md

# Improvements: src/core/base/common/base_utilities.py

Suggested improvements (automatically generated):
- Add unit tests covering core behavior and edge cases.
- Break large modules into smaller, testable components.
- Avoid heavy imports at module import time; import lazily where appropriate.
- Add type hints and explicit return types for public functions.
- Add logging and better error handling for file and IO operations.
- Consider dependency injection for filesystem and environment interactions.

LLM_CONTEXT_END

"""

"""Utilities used across base modules.

Small, well-typed helper functions and decorators used by agents and tools.
Focus on low-risk, testable behaviors: replacement helpers, logging setup,
and tool wrappers that record interactions to the fleet recorder when present.
"""
import argparse
import inspect
import json
import logging
import os
import re
import sys
import time
from pathlib import Path
from typing import Any, Callable, Union

from src.core.base.common.file_system_core import FileSystemCore
from src.core.base.lifecycle.base_agent import BaseAgent

# Regex for matching ANSI escape sequences (CSI codes)
_ansi_re = re.compile(r"\x1B\[[0-?]*[ -/]*[@-~]")
_fs = FileSystemCore()


def strip_ansi_codes(text: str) -> str:
    """
    """
