#!/usr/bin/env python3
"""
LLM_CONTEXT_START

## Source: src-old/core/base/common/hardware_core.description.md

# Description: src/core/base/common/hardware_core.py

Module docstring (if present):

    Core logic for Hardware Acceleration and NPU interaction.

Top-level members:
- Classes: HardwareCore

Notes:
- This description was auto-generated by scripts/generate_docs_for_src.py
## Source: src-old/core/base/common/hardware_core.improvements.md

# Improvements: src/core/base/common/hardware_core.py

Suggested improvements (automatically generated):
- Add unit tests covering core behavior and edge cases.
- Break large modules into smaller, testable components.
- Avoid heavy imports at module import time; import lazily where appropriate.
- Add type hints and explicit return types for public functions.
- Add logging and better error handling for file and IO operations.
- Consider dependency injection for filesystem and environment interactions.

LLM_CONTEXT_END
"""

"""Core logic for Hardware Acceleration and NPU interaction."""
from __future__ import annotations
# Copyright 2026 PyAgent Authors
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import logging
from typing import Optional

from src.core.base.common.base_core import BaseCore

try:
    import rust_core as rc
except ImportError:
    rc = None

logger = logging.getLogger("pyagent.hardware")


class HardwareCore(BaseCore):
    """
    Standard interface for hardware-specific optimizations (NPU, GPU).
    """

    def __init__(self, name: str = "HardwareCore", repo_root: Optional[str] = None) -> None:
        """Initializes the HardwareCore with optional name and repo_root."""
        super().__init__(name=name, repo_root=repo_root)
        self._npu_status = False

    def initialize_npu(self) -> bool:
        """Attempts to initialize NPU acceleration via Rust core."""
        if rc and hasattr(rc, "initialize_npu"):  # pylint: disable=no-member
            # pylint: disable=no-member
            result = rc.initialize_npu()
            self._npu_status = result == 0
            return self._npu_status
        return False

    def run_npu_model(self, model_path: str) -> bool:
        """Executes a model on the NPU."""
        if rc and hasattr(rc, "run_npu_model") and self._npu_status:  # pylint: disable=no-member
            # pylint: disable=no-member
            result = rc.run_npu_model(model_path)
            return result == 0
        return False
