#!/usr/bin/env python3
"""LLM_CONTEXT_START

## Source: src-old/core/base/common/metrics_core.description.md

# Description: src/core/base/common/metrics_core.py

Module docstring (if present):

    Core logic for metrics collection and performance analysis.

Top-level members:
- Classes: MetricRecord, AgentMetrics, MetricsCore

Notes:
- This description was auto-generated by scripts/generate_docs_for_src.py
## Source: src-old/core/base/common/metrics_core.improvements.md

# Improvements: src/core/base/common/metrics_core.py

Suggested improvements (automatically generated):
- Add unit tests covering core behavior and edge cases.
- Break large modules into smaller, testable components.
- Avoid heavy imports at module import time; import lazily where appropriate.
- Add type hints and explicit return types for public functions.
- Add logging and better error handling for file and IO operations.
- Consider dependency injection for filesystem and environment interactions.

LLM_CONTEXT_END

"""
from __future__ import annotations


# Copyright 2026 PyAgent Authors
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# limitations under the License.
"""
Core logic for metrics collection and performance analysis.
"""


import logging
import time
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Tuple

from .base_core import BaseCore

try:
    import rust_core as rc
except ImportError:
    rc = None

logger = logging.getLogger("pyagent.metrics")


@dataclass
class MetricRecord:
    """Represents a single metric data point."""

    name: str
    value: float
    timestamp: float = field(default_factory=time.time)
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class AgentMetrics:
    """Manages execution metrics and statistics for an agent."""

    files_processed: int = 0
    files_modified: int = 0
    agents_applied: dict[str, int] = field(default_factory=dict)
    start_time: float = field(default_factory=time.time)
    end_time: float | None = None

    def record_file_processed(self, modified: bool = False) -> None:
        """Records a file being processed."""
        self.files_processed += 1
        if modified:
            self.files_modified += 1

    def record_agent_applied(self, agent_name: str) -> None:
        """Records an agent being applied."""
        self.agents_applied[agent_name] = self.agents_applied.get(agent_name, 0) + 1

    def finalize(self) -> None:
        """Finalizes the metrics."""
        self.end_time = time.time()

    def get_summary(self, dry_run: bool = False) -> str:
        """Returns a string summary of the execution."""
        if not self.end_time:
            self.finalize()
        elapsed = self.end_time - self.start_time

        summary = f"""
=== Agent Execution Summary ===
Files processed: {self.files_processed}
Files modified:  {self.files_modified}
Execution time:  {elapsed:.2f}s
Dry-run mode:    {"Yes" if dry_run else "No"}

Agents applied:
"""
        # Build summary lines functionally
        lines = list(map(lambda item: f"  - {item[0]}: {item[1]} files\n", sorted(self.agents_applied.items())))
        return summary + "".join(lines)

    def to_dict(self) -> dict[str, Any]:
        """
        """
