#!/usr/bin/env python3
"""LLM_CONTEXT_START

## Source: src-old/core/base/common/scaling_core.description.md

# Description: src/core/base/common/scaling_core.py

Module docstring (if present):

    Unified Scaling Core for PyAgent.
    Handles resource calculation, fleet expansion logic, and anti-flapping protocols.

Top-level members:
- Classes: ScalingCore

Notes:
- This description was auto-generated by scripts/generate_docs_for_src.py
## Source: src-old/core/base/common/scaling_core.improvements.md

# Improvements: src/core/base/common/scaling_core.py

Suggested improvements (automatically generated):
- Add unit tests covering core behavior and edge cases.
- Break large modules into smaller, testable components.
- Avoid heavy imports at module import time; import lazily where appropriate.
- Add type hints and explicit return types for public functions.
- Add logging and better error handling for file and IO operations.
- Consider dependency injection for filesystem and environment interactions.

LLM_CONTEXT_END

"""

"""Unified Scaling Core for PyAgent."""
from __future__ import annotations

# Copyright 2026 PyAgent Authors
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
import math
from typing import List

from src.core.base.common.base_core import BaseCore

try:
    import rust_core as rc  # pylint: disable=import-error
except ImportError:
    rc = None


class ScalingCore(BaseCore):
    """Core implementation for computing scaling decisions.
    Optimized for high-frequency resource monitoring.
    """

    def __init__(self) -> None:
        """Initializes the ScalingCore with an empty load history."""
        super().__init__()
        self.load_history: List[float] = []

    def compute_moving_average(self, current_load: float, window_size: int = 10) -> float:
        """Compute the SMA for load balancing."""
        if rc and hasattr(rc, "compute_ma_rust"):  # pylint: disable=no-member
            return rc.compute_ma_rust(self.load_history, current_load, window_size)  # pylint: disable=no-member

        self.load_history.append(current_load)
        if len(self.load_history) > window_size:
            self.load_history.pop(0)
        return sum(self.load_history) / len(self.load_history)

    def calculate_required_replicas(self, avg_load: float, target_load: float, current_replicas: int) -> int:
        """Calculate the target replica count."""
        if avg_load <= 0:
            return current_replicas
        return math.ceil(current_replicas * (avg_load / target_load))
