from typing import Any, Dict, List, Optional

class PostgresBackend:
    conn_str: str

    def __init__(self, conn_str: Optional[str] = None) -> None: ...
    def connect(self) -> None: ...
    def close(self) -> None: ...

    # Worker management
    def register_worker(
        self,
        worker_id: str,
        hostname: Optional[str] = None,
        capabilities: Optional[List[Any]] = None,
        geo_region: Optional[str] = None,
    ) -> None: ...
    def heartbeat_worker(self, worker_id: str) -> None: ...

    # Task lifecycle
    def get_pending_tasks(self) -> List[Dict[str, Any]]: ...
    def claim_task(self, worker_id: str, capabilities: Optional[List[Any]] = None) -> Optional[Dict[str, Any]]: ...
    def reassign_zombie_tasks(self, timeout_minutes: int = 5) -> None: ...
    def mark_task_status(
        self, task_id: str, status: str, result: Optional[Dict[str, Any]] = None, error: Optional[str] = None
    ) -> None: ...

    # Caching and results
    def build_task_signature(self, agent_name: str, task: Dict[str, Any]) -> str: ...
    def get_cached_result(self, agent_name: str, signature: str) -> Optional[Dict[str, Any]]: ...
    def store_cached_result(
        self, agent_name: str, signature: str, task: Dict[str, Any], result: Dict[str, Any]
    ) -> None: ...

    # Logging / events / memory
    def log(self, source: str, message: str) -> None: ...
    def record_execution_event(
        self,
        agent_name: str,
        task: Dict[str, Any],
        status: str,
        result: Optional[Dict[str, Any]] = None,
        error: Optional[str] = None,
    ) -> None: ...
    def append_memory_entry(self, agent_name: str, summary: str, metadata: Optional[Dict[str, Any]] = None) -> None: ...

    # Rules / config helpers
    def get_rule_overrides(self, key: str) -> Dict[str, Any]: ...
