#!/usr/bin/env python3
# Copyright 2026 PyAgent Authors
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""LLM_CONTEXT_START

## Source: src-old/interface/slash_commands/__init__.description.md

# Description: src/interface/slash_commands/__init__.py

Module docstring (if present):

    SlashCommands - Modular command system for chat prompts.

    Commands are organized in the `commands/` subdirectory and auto-discovered.
    Each command module should use the @register decorator to register handlers.

    Example command module (commands/greet.py):
        from src.interface.slash_commands import register, CommandContext, CommandResult

        @register("greet", description="Greet someone", aliases=["hi", "hello"])
        def cmd_greet(ctx: CommandContext) -> CommandResult:
            return CommandResult.ok(f"[Hello, {ctx.first_arg or 'world'}!]")

    Phase 24: Advanced Observability & Parsing

Top-level members:
- (no top-level classes or functions)

Notes:
- This description was auto-generated by scripts/generate_docs_for_src.py
## Source: src-old/interface/slash_commands/__init__.improvements.md

# Improvements: src/interface/slash_commands/__init__.py

Suggested improvements (automatically generated):
- Add unit tests covering core behavior and edge cases.
- Break large modules into smaller, testable components.
- Avoid heavy imports at module import time; import lazily where appropriate.
- Add type hints and explicit return types for public functions.
- Add logging and better error handling for file and IO operations.
- Consider dependency injection for filesystem and environment interactions.

LLM_CONTEXT_END

"""

"""
SlashCommands - Modular command system for chat prompts.

Commands are organized in the `commands/` subdirectory and auto-discovered.
Each command module should use the @register decorator to register handlers.

Example command module (commands/greet.py):
from src.interface.slash_commands import register, CommandContext, CommandResult

    @register("greet", description="Greet someone", aliases=["hi", "hello"])
    def cmd_greet(ctx: CommandContext) -> CommandResult:
        return CommandResult.ok(f"[Hello, {ctx.first_arg or 'world'}!]")

Phase 24: Advanced Observability & Parsing
"""

# Convenience functions
from src.interface.slash_commands.api import (
    execute_command,
    get_slash_commands,
    process_prompt,
)
from src.interface.slash_commands.core import (
    CommandContext,
    CommandDefinition,
    CommandRegistry,
    CommandResult,
    ParsedCommand,
    ProcessedPrompt,
    SlashCommands,
    parse_commands,
)
from src.interface.slash_commands.loader import (
    discover_command_modules,
    load_commands,
    reload_commands,
)
from src.interface.slash_commands.registry import (
    command,
    get_global_registry,
    register,
    register_command,
)

__all__ = [
    # Core classes
    "SlashCommands",
    "CommandContext",
    "CommandResult",
    "CommandDefinition",
    "CommandRegistry",
    "ParsedCommand",
    "ProcessedPrompt",
    # Parsing
    "parse_commands",
    # Registry
    "get_global_registry",
    "register",
    "register_command",
    "command",
    # Loader
    "load_commands",
    "discover_command_modules",
    "reload_commands",
    # API
    "get_slash_commands",
    "process_prompt",
    "execute_command",
]
