#!/usr/bin/env python3
"""LLM_CONTEXT_START

## Source: src-old/core/base/common/utils/hash_registry.description.md

# Description: src/core/base/common/utils/hash_registry.py

Module docstring (if present):

    HashRegistry - Unified hashing utilities with multiple backends.

    Inspired by vLLM's hashing.py patterns for flexible hash function selection.

    Supports:
    - SHA-256 (cryptographic, FIPS-compliant)
    - MD5 (fast, non-cryptographic)
    - xxHash (fastest, non-cryptographic)
    - FNV-1a (Rust-native fast hash)
    - Safe hash (auto-selects based on environment)

    Phase 17: vLLM Pattern Integration (P2)

Top-level members:
- Classes: HashAlgorithm, ContentHasher
- Functions: _is_fips_mode, is_fips_mode, hash_sha256, hash_sha1, hash_md5, hash_xxhash64, hash_xxhash128, _fnv1a_hash, hash_fnv1a, safe_hash

Notes:
- This description was auto-generated by scripts/generate_docs_for_src.py
## Source: src-old/core/base/common/utils/hash_registry.improvements.md

# Improvements: src/core/base/common/utils/hash_registry.py

Suggested improvements (automatically generated):
- Add unit tests covering core behavior and edge cases.
- Break large modules into smaller, testable components.
- Avoid heavy imports at module import time; import lazily where appropriate.
- Add type hints and explicit return types for public functions.
- Add logging and better error handling for file and IO operations.
- Consider dependency injection for filesystem and environment interactions.

LLM_CONTEXT_END

"""
from __future__ import annotations


# Copyright 2026 PyAgent Authors
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
HashRegistry - Unified hashing utilities with multiple backends.

Inspired by vLLM's hashing.py patterns for flexible hash function selection.

Supports:
- SHA-256 (cryptographic, FIPS-compliant)
- MD5 (fast, non-cryptographic)
- xxHash (fastest, non-cryptographic)
- FNV-1a (Rust-native fast hash)
- Safe hash (auto-selects based on environment)

Phase 17: vLLM Pattern Integration (P2)
"""
import hashlib
import json
import os
from enum import Enum, auto
from functools import lru_cache
from typing import Callable, Union

# Rust acceleration
try:
    import rust_core as rc

    RUST_AVAILABLE = True
except ImportError:
    RUST_AVAILABLE = False

# Optional xxhash
try:
    import xxhash

    XXHASH_AVAILABLE = True
except ImportError:
    XXHASH_AVAILABLE = False


class HashAlgorithm(Enum):
    """
    """
