#!/usr/bin/env python3
"""
LLM_CONTEXT_START

## Source: src-old/core/base/common/utils/scheduled_execution.description.md

# Description: src/core/base/common/utils/scheduled_execution.py

Module docstring (if present):

    Auto-extracted class from agent.py

Top-level members:
- Classes: ScheduledExecution

Notes:
- This description was auto-generated by scripts/generate_docs_for_src.py
## Source: src-old/core/base/common/utils/scheduled_execution.improvements.md

# Improvements: src/core/base/common/utils/scheduled_execution.py

Suggested improvements (automatically generated):
- Add unit tests covering core behavior and edge cases.
- Break large modules into smaller, testable components.
- Avoid heavy imports at module import time; import lazily where appropriate.
- Add type hints and explicit return types for public functions.
- Add logging and better error handling for file and IO operations.
- Consider dependency injection for filesystem and environment interactions.

LLM_CONTEXT_END
"""

from __future__ import annotations

# Copyright 2026 PyAgent Authors
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


"""Auto-extracted class from agent.py"""


from dataclasses import dataclass, field
from typing import Any

from src.core.base.common.utils.helpers import _empty_dict_str_any
from src.core.base.lifecycle.version import VERSION

__version__ = VERSION


@dataclass
class ScheduledExecution:
    """A scheduled agent execution.

    Attributes:
        name: Schedule name.
        cron: Cron expression (simplified).
        agent_config: Agent configuration.
        enabled: Whether schedule is enabled.
        last_run: Last run timestamp.
        next_run: Next run timestamp.
    """

    name: str
    cron: str  # Simplified: "hourly", "daily", "weekly", or HH:MM
    agent_config: dict[str, Any] = field(default_factory=_empty_dict_str_any)
    enabled: bool = True
    last_run: float | None = None
    next_run: float | None = None
