#!/usr/bin/env python3
"""LLM_CONTEXT_START

## Source: src-old/core/base/common/utils/validation_rule_manager.description.md

# Description: src/core/base/common/utils/validation_rule_manager.py

Module docstring (if present):

    Manager for validation rules.
    (Facade for src.core.base.common.validation_core)

Top-level members:
- Classes: ValidationRuleManager

Notes:
- This description was auto-generated by scripts/generate_docs_for_src.py
## Source: src-old/core/base/common/utils/validation_rule_manager.improvements.md

# Improvements: src/core/base/common/utils/validation_rule_manager.py

Suggested improvements (automatically generated):
- Add unit tests covering core behavior and edge cases.
- Break large modules into smaller, testable components.
- Avoid heavy imports at module import time; import lazily where appropriate.
- Add type hints and explicit return types for public functions.
- Add logging and better error handling for file and IO operations.
- Consider dependency injection for filesystem and environment interactions.

LLM_CONTEXT_END

"""

from __future__ import annotations

# Copyright 2026 PyAgent Authors

"""
Manager for validation rules.
(Facade for src.core.base.common.validation_core)
"""

from pathlib import Path
from typing import Any

from src.core.base.common.models import ValidationRule
from src.core.base.common.validation_core import ValidationCore


class ValidationRuleManager:
    """Manages validation rules for agent content."""

    def __init__(self, core: ValidationCore | None = None) -> None:
        self._core = core or ValidationCore()
        self._rules: dict[str, Any] = {}
        self.rules = self._rules

    def add_rule(
        self,
        name_or_rule: str | ValidationRule,
        pattern: str = "",
        message: str = "Validation failed",
        severity: str = "error",
        **kwargs,
    ) -> None:
        """Add a validation rule. Supports both legacy signature and ValidationRule object."""
        if hasattr(name_or_rule, "name"):
            # It's a ValidationRule object
            rule = name_or_rule
            self._core.add_rule(rule)
            self._rules[rule.name] = rule
            return

        # Legacy dict-based registration
        rule_obj = {
            "name": name_or_rule,
            "pattern": pattern,
            "message": message,
            "severity": severity,
            **kwargs,
        }
        self._rules[name_or_rule] = rule_obj
        self._core.register_rule(name_or_rule, rule_obj)

    def validate(self, file_path: Path | str, content: str) -> list[dict[str, Any]]:
        """Validate content against rules. Legacy support."""
        if not isinstance(file_path, Path):
            file_path = Path(file_path)
        return self._core.validate_content_by_rules(file_path, content)
