# Extracted from: C:\DEV\PyAgent\.external\0xSojalSec-VolWeb\evidences\migrations\0001_initial.py
# Generated by Django 4.2.4 on 2024-03-24 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cases", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Evidence",
            fields=[
                ("dump_id", models.AutoField(primary_key=True, serialize=False)),
                ("dump_name", models.CharField(max_length=250)),
                ("dump_etag", models.CharField(max_length=256)),
                (
                    "dump_os",
                    models.CharField(
                        choices=[("Windows", "Windows"), ("Linux", "Linux")],
                        max_length=10,
                    ),
                ),
                ("dump_status", models.IntegerField(default=0)),
                ("dump_logs", models.JSONField(null=True)),
                (
                    "dump_linked_case",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="cases.case"),
                ),
            ],
        ),
    ]
