"""Domain types for the PyAgent core architecture."""

from .AccessibilityIssue import AccessibilityIssue
from .AccessibilityIssueType import AccessibilityIssueType
from .AccessibilityReport import AccessibilityReport
from .AccessibilitySeverity import AccessibilitySeverity
from .ARIAAttribute import ARIAAttribute
from .ChangelogEntry import ChangelogEntry
from .CodeLanguage import CodeLanguage
from .CodeMetrics import CodeMetrics
from .CodeSmell import CodeSmell
from .ColorContrastResult import ColorContrastResult
from .ComplianceCategory import ComplianceCategory
from .ComplianceResult import ComplianceResult
from .ConsistencyIssue import ConsistencyIssue
from .DependencyNode import DependencyNode
from .DependencyType import DependencyType
from .DiffResult import DiffResult
from .DiffViewMode import DiffViewMode
from .EntryTemplate import EntryTemplate
from .FeedFormat import FeedFormat
from .GroupingStrategy import GroupingStrategy
from .LinkedReference import LinkedReference
from .LocalizationLanguage import LocalizationLanguage
from .LocalizedEntry import LocalizedEntry
from .MigrationRule import MigrationRule
from .MigrationStatus import MigrationStatus
from .ModernizationSuggestion import ModernizationSuggestion
from .MonorepoEntry import MonorepoEntry
from .OptimizationSuggestion import OptimizationSuggestion
from .OptimizationType import OptimizationType
from .ProfilingCategory import ProfilingCategory
from .ProfilingSuggestion import ProfilingSuggestion
from .QualityScore import QualityScore
from .RefactoringPattern import RefactoringPattern
from .ReleaseNote import ReleaseNote
from .ReviewCategory import ReviewCategory
from .ReviewFinding import ReviewFinding
from .SearchResult import SearchResult
from .SecurityIssueType import SecurityIssueType
from .SecurityVulnerability import SecurityVulnerability
from .StyleRule import StyleRule
from .StyleRuleSeverity import StyleRuleSeverity
from .TemplateManager import TemplateManager
from .TestGap import TestGap
from .VersioningStrategy import VersioningStrategy
from .WCAGLevel import WCAGLevel
