# Extracted from: C:\DEV\PyAgent\src\external_candidates\ingested\_0xsojalsec_volweb.py\symbols.py\migrations.py\_0001_initial_112f1699f86f.py
# NOTE: extracted with static-only rules; review before use

# Extracted from: C:\DEV\PyAgent\.external\0xSojalSec-VolWeb\symbols\migrations\0001_initial.py

# Generated by Django 4.2.4 on 2024-03-24 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Symbol",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                (
                    "os",
                    models.CharField(
                        choices=[("Windows", "Windows"), ("Linux", "Linux")],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(max_length=500)),
                ("symbols_file", models.FileField(upload_to="symbols/")),
            ],
        ),
    ]
