#!/usr/bin/env python3
# Copyright 2026 PyAgent Authors
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""LLM_CONTEXT_START

## Source: src-old/logic/agents/swarm/changelog_entry.description.md

# Description: src/logic/agents/swarm/changelog_entry.py

Module docstring (if present):

    Changelog entry.py module.

Top-level members:
- Classes: ChangelogEntry

Notes:
- This description was auto-generated by scripts/generate_docs_for_src.py
## Source: src-old/logic/agents/swarm/changelog_entry.improvements.md

# Improvements: src/logic/agents/swarm/changelog_entry.py

Suggested improvements (automatically generated):
- Add unit tests covering core behavior and edge cases.
- Break large modules into smaller, testable components.
- Avoid heavy imports at module import time; import lazily where appropriate.
- Add type hints and explicit return types for public functions.
- Add logging and better error handling for file and IO operations.
- Consider dependency injection for filesystem and environment interactions.

LLM_CONTEXT_END

"""

"""
Changelog entry.py module.
"""

from dataclasses import dataclass, field
from typing import List


@dataclass
class ChangelogEntry:
    """Represents a single entry in the fleet-wide changelog."""

    category: str
    description: str
    version: str
    date: str
    priority: int
    severity: str
    tags: List[str] = field(default_factory=list)
    linked_issues: List[str] = field(default_factory=list)
