version: '3.8'
services:
  fleet_master:
    build:
      context: ..
      dockerfile: deploy/Dockerfile.fleet
    ports:
      - "${BACKEND_PORT:-444}:${BACKEND_PORT:-444}"
    environment:
      - NODE_TYPE=MASTER
      - HOST=${HOST:-0.0.0.0}
      - BACKEND_PORT=${BACKEND_PORT:-444}

  agent_node_0:
    build:
      context: ..
      dockerfile: deploy/Dockerfile.fleet
    environment:
      - NODE_TYPE=WORKER
      - MASTER_URL=http://fleet_master:${BACKEND_PORT:-444}

  agent_node_1:
    build:
      context: ..
      dockerfile: deploy/Dockerfile.fleet
    environment:
      - NODE_TYPE=WORKER
      - MASTER_URL=http://fleet_master:${BACKEND_PORT:-444}
