#!/usr/bin/env python3
"""
LLM_CONTEXT_START

## Source: src-old/core/base/common/models/__init__.description.md

# Description: src/core/base/common/models/__init__.py

Module docstring (if present):

    Data models for PyAgent.
    Unified entry point for re-exporting all sub-modules via lazy loading.

Top-level members:
- Functions: __getattr__, __dir__

Notes:
- This description was auto-generated by scripts/generate_docs_for_src.py
## Source: src-old/core/base/common/models/__init__.improvements.md

# Improvements: src/core/base/common/models/__init__.py

Suggested improvements (automatically generated):
- Add unit tests covering core behavior and edge cases.
- Break large modules into smaller, testable components.
- Avoid heavy imports at module import time; import lazily where appropriate.
- Add type hints and explicit return types for public functions.
- Add logging and better error handling for file and IO operations.
- Consider dependency injection for filesystem and environment interactions.

LLM_CONTEXT_END
"""

"""Safe export surface for frequently-used model names.

This module provides minimal, import-safe symbols for test collection
and lightweight modules. It attempts to import the real implementations
but falls back to None placeholders to avoid circular import problems
during pytest collection. Replace with full lazy-loading if needed.
"""

from typing import Any
import importlib
from types import ModuleType

# Start with minimal placeholders to avoid AttributeError during early imports
_export_names: dict[str, Any] = {}


def _try_import_module(submod: str) -> ModuleType | None:
    try:
        return importlib.import_module(f"{__package__}.{submod}")
    except Exception:
        return None


# Try to import submodules and copy public names into this package namespace
_submodules = (
    "base_models",
    "communication_models",
    "core_enums",
    "fleet_models",
    "agent_models",
    "_factories",
)
for _sub in _submodules:
    _m = _try_import_module(_sub)
    if _m is None:
        continue
    for _name in dir(_m):
        if _name.startswith("_"):
            continue
        try:
            _export_names[_name] = getattr(_m, _name)
        except Exception:
            # Skip names that raise on access
            continue

globals().update(_export_names)

__all__ = [name for name in _export_names.keys()]

# Provide lightweight placeholders for key names if the real implementations
# could not be imported (prevents ImportError during pytest collection).
_placeholder_names = (
    "AgentConfig",
    "CacheEntry",
    "EventType",
    "PromptTemplate",
    "FailureClassification",
    "AgentState",
    "ResponseQuality",
)
for _name in _placeholder_names:
    if _name not in globals():

        class _Placeholder:
            pass

        globals()[_name] = _Placeholder
        __all__.append(_name)
