#!/usr/bin/env python3
"""
LLM_CONTEXT_START

## Source: src-old/logic/agents/cognitive/context/utils/cross_repo_analyzer.description.md

# Description: src/logic/agents/cognitive/context/utils/cross_repo_analyzer.py

Module docstring (if present):

    Auto-extracted class from agent_context.py

Top-level members:
- Classes: CrossRepoAnalyzer

Notes:
- This description was auto-generated by scripts/generate_docs_for_src.py
## Source: src-old/logic/agents/cognitive/context/utils/cross_repo_analyzer.improvements.md

# Improvements: src/logic/agents/cognitive/context/utils/cross_repo_analyzer.py

Suggested improvements (automatically generated):
- Add unit tests covering core behavior and edge cases.
- Break large modules into smaller, testable components.
- Avoid heavy imports at module import time; import lazily where appropriate.
- Add type hints and explicit return types for public functions.
- Add logging and better error handling for file and IO operations.
- Consider dependency injection for filesystem and environment interactions.

LLM_CONTEXT_END
"""

from __future__ import annotations

# Copyright 2026 PyAgent Authors
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


"""Auto-extracted class from agent_context.py"""

from src.core.base.version import VERSION
from src.logic.agents.cognitive.context.utils.CrossRepoContext import CrossRepoContext
from typing import Dict, List

__version__ = VERSION


class CrossRepoAnalyzer:
    """Analyzes context across multiple repositories.

    Provides functionality to find related code and patterns
    across different repositories.

    Example:
        >>> analyzer=CrossRepoAnalyzer()
        >>> analyzer.add_repository("owner / repo", "https://github.com / owner / repo")
        >>> results=analyzer.find_related_contexts("auth.py")
    """

    def __init__(self) -> None:
        """Initialize the cross-repo analyzer."""
        self.repositories: dict[str, CrossRepoContext] = {}
        self.repos: dict[str, dict[str, str]] = {}  # Add repos attribute

    def add_repo(self, name: str, url: str) -> None:
        """Add a repository."""
        self.repos[name] = {"name": name, "url": url}

    def analyze(self, file_path: str) -> list[CrossRepoContext]:
        """Analyze a file path across configured repositories.

        Compatibility wrapper used by tests.
        """
        return self.find_related_contexts(file_path)

    def find_common_patterns(self) -> list[str]:
        """Find common patterns across repos."""
        return []

    def add_repository(self, name: str, url: str) -> CrossRepoContext:
        """Add a repository for analysis.

        Args:
            name: Repository name.
            url: Repository URL.

        Returns:
            Created CrossRepoContext.
        """
        context = CrossRepoContext(repo_name=name, repo_url=url)
        self.repositories[name] = context
        return context

    def find_related_contexts(self, file_path: str) -> list[CrossRepoContext]:
        """Find related contexts across repositories.

        Args:
            file_path: Path to analyze.

        Returns:
            List of related cross - repo contexts.
        """
        results: list[CrossRepoContext] = []
        for repo in self.repositories.values():
            # Simplified matching
            repo.similarity_score = 0.5
            repo.related_files.append(file_path)
            results.append(repo)
        return results
