#!/usr/bin/env python3
"""LLM_CONTEXT_START

## Source: src-old/observability/improvements/archive_manager.description.md

# Description: src/observability/improvements/archive_manager.py

Module docstring (if present):

    Auto-extracted class from agent_improvements.py

Top-level members:
- Classes: ArchiveManager

Notes:
- This description was auto-generated by scripts/generate_docs_for_src.py
## Source: src-old/observability/improvements/archive_manager.improvements.md

# Improvements: src/observability/improvements/archive_manager.py

Suggested improvements (automatically generated):
- Add unit tests covering core behavior and edge cases.
- Break large modules into smaller, testable components.
- Avoid heavy imports at module import time; import lazily where appropriate.
- Add type hints and explicit return types for public functions.
- Add logging and better error handling for file and IO operations.
- Consider dependency injection for filesystem and environment interactions.

LLM_CONTEXT_END

"""

from __future__ import annotations

# Copyright 2026 PyAgent Authors
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


"""Auto-extracted class from agent_improvements.py"""


from src.core.base.lifecycle.version import VERSION

from .improvement import Improvement

__version__ = VERSION


class ArchiveManager:
    """Archives completed improvements."""

    def __init__(self) -> None:
        self.archived: list[Improvement] = []

    def archive(self, improvement: Improvement) -> None:
        self.archived.append(improvement)

    def restore(self, improvement_id: str) -> Improvement:
        for i, imp in enumerate(list(self.archived)):
            if imp.id == improvement_id:
                self.archived.pop(i)
                return imp
        raise KeyError(improvement_id)
