#!/usr/bin/env python3
"""
LLM_CONTEXT_START

## Source: src-old/observability/improvements/code_analyzer.description.md

# Description: src/observability/improvements/code_analyzer.py

Module docstring (if present):

    Auto-extracted class from agent_improvements.py

Top-level members:
- Classes: CodeAnalyzer

Notes:
- This description was auto-generated by scripts/generate_docs_for_src.py
## Source: src-old/observability/improvements/code_analyzer.improvements.md

# Improvements: src/observability/improvements/code_analyzer.py

Suggested improvements (automatically generated):
- Add unit tests covering core behavior and edge cases.
- Break large modules into smaller, testable components.
- Avoid heavy imports at module import time; import lazily where appropriate.
- Add type hints and explicit return types for public functions.
- Add logging and better error handling for file and IO operations.
- Consider dependency injection for filesystem and environment interactions.

LLM_CONTEXT_END
"""

from __future__ import annotations
# Copyright 2026 PyAgent Authors
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


"""Auto-extracted class from agent_improvements.py"""


from src.core.base.lifecycle.version import VERSION

from .improvement import Improvement

__version__ = VERSION


class CodeAnalyzer:
    """Suggests analysis tools based on improvement content."""

    def __init__(self) -> None:
        self.tools: list[str] = [
            "security scan",
            "linter",
            "type checker",
            "coverage",
        ]

    def suggest_tools(self, improvement: Improvement) -> list[str]:
        text = f"{improvement.title} {improvement.description}".lower()
        suggestions: list[str] = []
        if "sql" in text or "injection" in text or "security" in text:
            suggestions.append("Security scan")
            suggestions.append("Dependency vulnerability scan")
        if "type" in text:
            suggestions.append("Type checker")
        if "test" in text:
            suggestions.append("Coverage")
        if not suggestions:
            suggestions.append("Linter")
        return suggestions
