#!/usr/bin/env python3
"""LLM_CONTEXT_START

## Source: src-old/observability/improvements/doc_generator.description.md

# Description: src/observability/improvements/doc_generator.py

Module docstring (if present):

    Auto-extracted class from agent_improvements.py

Top-level members:
- Classes: DocGenerator

Notes:
- This description was auto-generated by scripts/generate_docs_for_src.py
## Source: src-old/observability/improvements/doc_generator.improvements.md

# Improvements: src/observability/improvements/doc_generator.py

Suggested improvements (automatically generated):
- Add unit tests covering core behavior and edge cases.
- Break large modules into smaller, testable components.
- Avoid heavy imports at module import time; import lazily where appropriate.
- Add type hints and explicit return types for public functions.
- Add logging and better error handling for file and IO operations.
- Consider dependency injection for filesystem and environment interactions.

LLM_CONTEXT_END

"""

from __future__ import annotations

# Copyright 2026 PyAgent Authors
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


"""Auto-extracted class from agent_improvements.py"""


from typing import Any, cast

from src.core.base.lifecycle.version import VERSION

from .improvement import Improvement

__version__ = VERSION


class DocGenerator:
    """Generates simple documentation text for improvements."""

    def __init__(self) -> None:
        self.templates: dict[str, str] = {
            "default": "## {title}\n\n{description}\n",
        }

    def generate(self, improvement: Improvement, include_metadata: bool = False) -> str:
        base = self.templates["default"].format(title=improvement.title, description=improvement.description)
        if include_metadata:
            meta = getattr(improvement, "metadata", None)
            if isinstance(meta, dict) and meta:
                base += "\n## Metadata\n"
                meta_dict = cast(dict[str, Any], meta)
                for k, v in meta_dict.items():
                    base += f"- {k}: {v}\n"
        return base
