#!/usr/bin/env python3
"""LLM_CONTEXT_START

## Source: src-old/observability/improvements/improvement_exporter.description.md

# Description: src/observability/improvements/improvement_exporter.py

Module docstring (if present):

    Auto-extracted class from agent_improvements.py

Top-level members:
- Classes: ImprovementExporter

Notes:
- This description was auto-generated by scripts/generate_docs_for_src.py
## Source: src-old/observability/improvements/improvement_exporter.improvements.md

# Improvements: src/observability/improvements/improvement_exporter.py

Suggested improvements (automatically generated):
- Add unit tests covering core behavior and edge cases.
- Break large modules into smaller, testable components.
- Avoid heavy imports at module import time; import lazily where appropriate.
- Add type hints and explicit return types for public functions.
- Add logging and better error handling for file and IO operations.
- Consider dependency injection for filesystem and environment interactions.

LLM_CONTEXT_END

"""

from __future__ import annotations

# Copyright 2026 PyAgent Authors
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


"""Auto-extracted class from agent_improvements.py"""


import json
from typing import Any

from src.core.base.lifecycle.version import VERSION

from .improvement import Improvement

__version__ = VERSION


class ImprovementExporter:
    """Exports improvements to json/csv."""

    def __init__(self) -> None:
        self.formats: list[str] = ["json", "csv"]

    def export(self, improvements: list[Improvement], format: str = "json") -> str:
        fmt = format.lower()
        if fmt == "json":
            rows: list[dict[str, Any]] = []
            for imp in improvements:
                rows.append(
                    {
                        "id": imp.id,
                        "title": imp.title,
                        "description": imp.description,
                    }
                )
            return json.dumps(rows)
        if fmt == "csv":
            lines = ["id,title,description"]
            for imp in improvements:
                lines.append(f"{imp.id},{imp.title},{imp.description}")
            return "\n".join(lines)
        raise ValueError("Unsupported format")
