#!/usr/bin/env python3
"""LLM_CONTEXT_START

## Source: src-old/observability/improvements/improvement_dashboard.description.md

# Description: src/observability/improvements/improvement_dashboard.py

Module docstring (if present):

    Auto-extracted class from agent_improvements.py

Top-level members:
- Classes: ImprovementDashboard

Notes:
- This description was auto-generated by scripts/generate_docs_for_src.py
## Source: src-old/observability/improvements/improvement_dashboard.improvements.md

# Improvements: src/observability/improvements/improvement_dashboard.py

Suggested improvements (automatically generated):
- Add unit tests covering core behavior and edge cases.
- Break large modules into smaller, testable components.
- Avoid heavy imports at module import time; import lazily where appropriate.
- Add type hints and explicit return types for public functions.
- Add logging and better error handling for file and IO operations.
- Consider dependency injection for filesystem and environment interactions.

LLM_CONTEXT_END

"""

from __future__ import annotations

# Copyright 2026 PyAgent Authors
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


"""Auto-extracted class from agent_improvements.py"""


from collections.abc import Callable

from src.core.base.lifecycle.version import VERSION

from .improvement import Improvement

__version__ = VERSION


class ImprovementDashboard:
    """Renders a lightweight dashboard and emits update callbacks."""

    def __init__(self) -> None:
        self._callbacks: list[Callable[[], None]] = []
        self._improvements: list[Improvement] = []

    def on_update(self, callback: Callable[[], None]) -> None:
        self._callbacks.append(callback)

    def add_improvement(self, improvement: Improvement) -> None:
        self._improvements.append(improvement)
        for cb in list(self._callbacks):
            cb()

    def render(self, improvements: list[Improvement]) -> str:
        lines = ["# Improvements Dashboard"]
        for imp in improvements:
            lines.append(f"- {imp.title}")
        return "\n".join(lines)
