#!/usr/bin/env python3
"""LLM_CONTEXT_START

## Source: src-old/observability/improvements/sla_level.description.md

# Description: src/observability/improvements/sla_level.py

Module docstring (if present):

    Auto-extracted class from agent_improvements.py

Top-level members:
- Classes: SLALevel

Notes:
- This description was auto-generated by scripts/generate_docs_for_src.py
## Source: src-old/observability/improvements/sla_level.improvements.md

# Improvements: src/observability/improvements/sla_level.py

Suggested improvements (automatically generated):
- Add unit tests covering core behavior and edge cases.
- Break large modules into smaller, testable components.
- Avoid heavy imports at module import time; import lazily where appropriate.
- Add type hints and explicit return types for public functions.
- Add logging and better error handling for file and IO operations.
- Consider dependency injection for filesystem and environment interactions.

LLM_CONTEXT_END

"""

from __future__ import annotations

# Copyright 2026 PyAgent Authors
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


"""Auto-extracted class from agent_improvements.py"""


from enum import Enum

from src.core.base.lifecycle.version import VERSION

__version__ = VERSION


class SLALevel(Enum):
    """SLA priority levels."""

    P0 = 1  # 24 hours
    P1 = 2  # 3 days
    P2 = 3  # 1 week
    P3 = 4  # 2 weeks
    P4 = 5  # 1 month
