#!/usr/bin/env python3
"""LLM_CONTEXT_START

## Source: src-old/observability/improvements/voting_system.description.md

# Description: src/observability/improvements/voting_system.py

Module docstring (if present):

    Auto-extracted class from agent_improvements.py

Top-level members:
- Classes: VotingSystem

Notes:
- This description was auto-generated by scripts/generate_docs_for_src.py
## Source: src-old/observability/improvements/voting_system.improvements.md

# Improvements: src/observability/improvements/voting_system.py

Suggested improvements (automatically generated):
- Add unit tests covering core behavior and edge cases.
- Break large modules into smaller, testable components.
- Avoid heavy imports at module import time; import lazily where appropriate.
- Add type hints and explicit return types for public functions.
- Add logging and better error handling for file and IO operations.
- Consider dependency injection for filesystem and environment interactions.

LLM_CONTEXT_END

"""

from __future__ import annotations

# Copyright 2026 PyAgent Authors
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


"""Auto-extracted class from agent_improvements.py"""


from typing import Any

from src.core.base.lifecycle.version import VERSION

__version__ = VERSION


class VotingSystem:
    """Manages voting on improvements."""

    def __init__(self) -> None:
        self.votes: dict[str, dict[str, int]] = {}

    def cast_vote(
        self,
        improvement_id: str,
        voter: str | None = None,
        vote_value: int = 1,
        voter_id: str | None = None,
        **_: Any,
    ) -> None:
        voter_key = voter_id or voter or "anonymous"
        self.votes.setdefault(improvement_id, {})[voter_key] = int(vote_value)

    def get_vote_count(self, improvement_id: str) -> int:
        votes = self.votes.get(improvement_id, {})
        return sum(1 for v in votes.values() if v > 0)

    def get_prioritized_list(self, improvement_ids: list[str]) -> list[str]:
        return sorted(
            list(improvement_ids),
            key=lambda imp_id: self.get_vote_count(imp_id),
            reverse=True,
        )
