#!/usr/bin/env python3
"""
LLM_CONTEXT_START

## Source: src-old/logic/agents/cognitive/context/models/branch_comparison.description.md

# Description: src/logic/agents/cognitive/context/models/branch_comparison.py

Module docstring (if present):

    Auto-extracted class from agent_context.py

Top-level members:
- Classes: BranchComparison

Notes:
- This description was auto-generated by scripts/generate_docs_for_src.py
## Source: src-old/logic/agents/cognitive/context/models/branch_comparison.improvements.md

# Improvements: src/logic/agents/cognitive/context/models/branch_comparison.py

Suggested improvements (automatically generated):
- Add unit tests covering core behavior and edge cases.
- Break large modules into smaller, testable components.
- Avoid heavy imports at module import time; import lazily where appropriate.
- Add type hints and explicit return types for public functions.
- Add logging and better error handling for file and IO operations.
- Consider dependency injection for filesystem and environment interactions.

LLM_CONTEXT_END
"""

from __future__ import annotations

# Copyright 2026 PyAgent Authors
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


"""Auto-extracted class from agent_context.py"""

from src.core.base.version import VERSION
from typing import List, TYPE_CHECKING
from dataclasses import dataclass, field

    pass
__version__ = VERSION


@dataclass
class BranchComparison:
    """Comparison of context across branches.

    Attributes:
        branch_a: First branch name.
        branch_b: Second branch name.
        files_only_in_a: Files only in branch A.
        files_only_in_b: Files only in branch B.
        modified_files: Files modified between branches.
    """

    branch_a: str
    branch_b: str
    files_only_in_a: list[str] = field(default_factory=lambda: [])
    files_only_in_b: list[str] = field(default_factory=lambda: [])
    modified_files: list[str] = field(default_factory=lambda: [])
