#!/usr/bin/env python3
"""LLM_CONTEXT_START

## Source: src-old/core/base/logic/agent_verification.description.md

# Description: src/core/base/logic/agent_verification.py

Module docstring (if present):

    Verification logic for agent outputs.
    Implements Stanford Reseach 'Anchoring Strength' and Keio University 'Self-Verification' paths.

Top-level members:
- (no top-level classes or functions)

Notes:
- This description was auto-generated by scripts/generate_docs_for_src.py
## Source: src-old/core/base/logic/agent_verification.improvements.md

# Improvements: src/core/base/logic/agent_verification.py

Suggested improvements (automatically generated):
- Add unit tests covering core behavior and edge cases.
- Break large modules into smaller, testable components.
- Avoid heavy imports at module import time; import lazily where appropriate.
- Add type hints and explicit return types for public functions.
- Add logging and better error handling for file and IO operations.
- Consider dependency injection for filesystem and environment interactions.

LLM_CONTEXT_END

"""

"""Agent Verification Module: Implements verification logic for agent outputs, 
including Stanford Research 'Anchoring Strength' 
and Keio University 'Self-Verification' methodologies.
"""
from __future__ import annotations

# Copyright 2026 PyAgent Authors
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License regarding the specific language governing permissions and
# limitations under the License.
from src.core.base.lifecycle.version import VERSION

# Phase 317: Modularized Verification Classes
from .verification.agent_verifier import AgentVerifier
from .verification.code_health_auditor import CodeHealthAuditor
from .verification.code_integrity_verifier import CodeIntegrityVerifier

__version__ = VERSION

__all__ = ["AgentVerifier", "CodeHealthAuditor", "CodeIntegrityVerifier"]
