#!/usr/bin/env python3
# Copyright 2026 PyAgent Authors
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import os
import ast
from pathlib import Path

def generate_catalog():
    """Phase 244: Scans src/logic/agents and generates detailed documentation."""
    agents_dir = Path("src/logic/agents")
    output_file = Path("docs/AGENTS.md")
    
    agent_data = []
    
    for root, _, files in os.walk(agents_dir):
        for file in files:
            if file.endswith(".py") and file != "__init__.py":
                file_path = Path(root) / file
                try:
                    with open(file_path, "r", encoding="utf-8") as f:
                        node = ast.parse(f.read())
                    
                    version = "0.0.0"
                    classes = []
                    
                    for item in node.body:
                        # Version extraction
                        if isinstance(item, ast.Assign):
                            for target in item.targets:
                                if isinstance(target, ast.Name) and target.id == "__version__":
                                    if isinstance(item.value, ast.Constant):
                                        version = str(item.value.value)
                                    elif isinstance(item.value, ast.Name):
                                        # Likely 'VERSION' import
                                        version = "CORE-LINKED"
                        
                        # Class extraction
                        if isinstance(item, ast.ClassDef):
                            # Check if it looks like an Agent class (usually inherits from BaseAgent or CoderAgent)
                            docstring = ast.get_docstring(item) or "No description provided."
                            # Just take the first line of docstring for the table
                            summary = docstring.strip().split('\n')[0]
                            classes.append({
                                "name": item.name,
                                "description": summary
                            })
                    
                    rel_path = str(file_path).replace("\\", "/")
                    category = file_path.parent.name.capitalize()
                    
                    for cls in classes:
                        agent_data.append({
                            "Category": category,
                            "Class": cls["name"],
                            "Version": version,
                            "Description": cls["description"],
                            "File": f"[{file_path.name}](../{rel_path})"
                        })
                except Exception as e:
                    print(f"Warning: Failed to parse {file_path}: {e}")

    # Sort data
    agent_data.sort(key=lambda x: (x["Category"], x["Class"]))

    # Generate Markdown
    md = "# 🤖 PyAgent Swarm Catalog\n\n"
    md += "This document lists all specialized agents available in the PyAgent fleet. "
    md += "It is automatically generated by the `generate_agent_catalog.py` script.\n\n"
    md += "## 📊 Statistics\n"
    md += f"- **Total Agents Found**: {len(agent_data)}\n"
    md += f"- **Categories**: {len(set(a['Category'] for a in agent_data))}\n\n"
    
    md += "## 📋 Agent Manifest\n\n"
    md += "| Category | Agent | Version | Description | Source |\n"
    md += "| :--- | :--- | :--- | :--- | :--- |\n"
    
    for a in agent_data:
        md += f"| {a['Category']} | `{a['Class']}` | {a['Version']} | {a['Description']} | {a['File']} |\n"

    # Write output
    output_file.parent.mkdir(parents=True, exist_ok=True)
    output_file.write_text(md, encoding="utf-8")
    print(f"Catalog successfully generated: {output_file}")

if __name__ == "__main__":
    generate_catalog()