# -*- coding: utf-8 -*-
"""Extracted test classes from test_agent_stats.py."""

__all__ = [
    "TestABComparisonEngine",
    "TestAggregation",
    "TestAggregationAdvanced",
    "TestAlertSeverity",
    "TestAlerting",
    "TestAnnotationManager",
    "TestAnomalyDetection",
    "TestBenchmarking",
    "TestBenchmarkingAdvanced",
    "TestCSVExport",
    "TestCaching",
    "TestCachingAdvanced",
    "TestCloudExporter",
    "TestComparison",
    "TestComparisonReports",
    "TestCompression",
    "TestCorrelationAnalyzer",
    "TestCoverageMetrics",
    "TestCustomMetrics",
    "TestDerivedMetricCalculator",
    "TestDocstrings",
    "TestEdgeCases",
    "TestExportFormats",
    "TestExportFormatsAdvanced",
    "TestFiltering",
    "TestForecasting",
    "TestIntegration",
    "TestIntegrationAdvanced",
    "TestMetricFiltering",
    "TestMetricNamespaceManager",
    "TestMetricType",
    "TestPathLibUsage",
    "TestPerformanceMetrics",
    "TestRealTimeStatsStreaming",
    "TestReporting",
    "TestReportingWithInsights",
    "TestRetentionPolicies",
    "TestSession7Dataclasses",
    "TestSession7Enums",
    "TestSnapshots",
    "TestStatisticalSummaries",
    "TestStatisticalSummariesAdvanced",
    "TestStatsABComparison",
    "TestStatsAPIServer",
    "TestStatsAccessControl",
    "TestStatsAgent",
    "TestStatsAnnotationPersistence",
    "TestStatsBackupAndRestore",
    "TestStatsChangeNotificationSystem",
    "TestStatsCompressionAlgorithms",
    "TestStatsExportToMonitoringPlatforms",
    "TestStatsFederation",
    "TestStatsFederationAcrossSources",
    "TestStatsForecastingAccuracy",
    "TestStatsMetricFormulaCalculation",
    "TestStatsNamespaceIsolation",
    "TestStatsQueryPerformance",
    "TestStatsRetentionPolicyEnforcement",
    "TestStatsRollup",
    "TestStatsRollupCalculations",
    "TestStatsSnapshotCreationAndRestore",
    "TestStatsStreamer",
    "TestStatsSubscriptionAndNotification",
    "TestStatsThresholdAlerting",
    "TestSubscriptionManager",
    "TestThresholdsAndAlerting",
    "TestTimeSeries",
    "TestTimeSeriesStorage",
    "TestTrendAnalysis",
    "TestTrendAnalysisAdvanced",
    "TestValidation",
    "TestVisualization",
    "TestVisualizationAdvanced",
    "TestVisualizationGeneration",
]

from .test_stats_UNIT import *  # noqa: F401, F403
from .test_stats_INTEGRATION import *  # noqa: F401, F403
from .advanced import *  # noqa: F401, F403
from .edge_cases import *  # noqa: F401, F403
from .test_stats_PERFORMANCE import *  # noqa: F401, F403
