#!/usr/bin/env python3
"""
LLM_CONTEXT_START

## Source: src-old/logic/agents/development/mixins/agent/agent_style_mixin.description.md

# Description: src/logic/agents/development/mixins/agent/agent_style_mixin.py

Module docstring (if present):

    Style enforcement logic for CoderAgent.

Top-level members:
- Classes: AgentStyleMixin

Notes:
- This description was auto-generated by scripts/generate_docs_for_src.py
## Source: src-old/logic/agents/development/mixins/agent/agent_style_mixin.improvements.md

# Improvements: src/logic/agents/development/mixins/agent/agent_style_mixin.py

Suggested improvements (automatically generated):
- Add unit tests covering core behavior and edge cases.
- Break large modules into smaller, testable components.
- Avoid heavy imports at module import time; import lazily where appropriate.
- Add type hints and explicit return types for public functions.
- Add logging and better error handling for file and IO operations.
- Consider dependency injection for filesystem and environment interactions.

LLM_CONTEXT_END
"""

from __future__ import annotations
# Copyright 2026 PyAgent Authors
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Style enforcement logic for CoderAgent."""

# pylint: disable=too-many-ancestors


from typing import Any

from src.core.base.common.types.style_rule import StyleRule


class AgentStyleMixin:
    """Mixin for managing and checking code style rules."""

    def add_style_rule(self, rule: StyleRule) -> None:
        """Add a custom style rule."""
        if not hasattr(self, "_style_rules"):
            self._style_rules = []
        self._style_rules.append(rule)

    def remove_style_rule(self, rule_name: str) -> bool:
        """Remove a style rule by name."""
        if not hasattr(self, "_style_rules"):
            return False
        for i, rule in enumerate(self._style_rules):
            if rule.name == rule_name:
                del self._style_rules[i]
                return True
        return False

    def enable_style_rule(self, rule_name: str) -> bool:
        """Enable a style rule."""
        if not hasattr(self, "_style_rules"):
            return False
        for rule in self._style_rules:
            if rule.name == rule_name:
                rule.enabled = True
                return True
        return False

    def disable_style_rule(self, rule_name: str) -> bool:
        """Disable a style rule."""
        if not hasattr(self, "_style_rules"):
            return False
        for rule in self._style_rules:
            if rule.name == rule_name:
                rule.enabled = False
                return True
        return False

    def check_style(self, content: str) -> list[dict[str, Any]]:
        """Check code against all enabled style rules."""
        if hasattr(self, "core") and hasattr(self, "_style_rules"):
            return self.core.check_style(content, self._style_rules)
        return []

    def auto_fix_style(self, content: str) -> tuple[str, int]:
        """Apply auto-fixes for style violations."""
        if hasattr(self, "core") and hasattr(self, "_style_rules"):
            return self.core.auto_fix_style(content, self._style_rules)
        return content, 0
