#!/usr/bin/env python3
from __future__ import annotations
# Copyright 2026 PyAgent Authors
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""LLM_CONTEXT_START

## Source: src-old/interface/commands/parser.description.md

# Description: src/interface/commands/parser.py

Module docstring (if present):

    Slash command parser and executor.

Top-level members:
- Classes: CommandParser
- Functions: parse_commands

Notes:
- This description was auto-generated by scripts/generate_docs_for_src.py
## Source: src-old/interface/commands/parser.improvements.md

# Improvements: src/interface/commands/parser.py

Suggested improvements (automatically generated):
- Add unit tests covering core behavior and edge cases.
- Break large modules into smaller, testable components.
- Avoid heavy imports at module import time; import lazily where appropriate.
- Add type hints and explicit return types for public functions.
- Add logging and better error handling for file and IO operations.
- Consider dependency injection for filesystem and environment interactions.

LLM_CONTEXT_END

"""


import importlib.util
import logging
import os
import re
import sys
import time
from typing import Any, ClassVar

# Imports can fail when the package is referenced via the
# `src.` prefix in sys.path.  We attempt a normal relative import first
# then fall back to dynamically loading the module files by path.

_pkg_dir = os.path.dirname(__file__)

"""
Slash command parser and executor.
"""
def _load_local(name: str):
    """
    """
