FROM python:3.10-slim

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENV AGENT_TYPE=SQLAgent
CMD ["python", "src/logic/agents/intelligence/SQLQueryAgent.py"]
