#!/usr/bin/env python3
"""LLM_CONTEXT_START

## Source: src-old/logic/agents/analysis/tech_debt_core.description.md

# Description: src/logic/agents/analysis/tech_debt_core.py

Module docstring (if present):

    TechDebtCore: Core logic for technical debt analysis and management in PyAgent.
    Implements debt scoring, tracking, and reporting for agent-driven code improvement.

Top-level members:
- Classes: TechDebtCore

Notes:
- This description was auto-generated by scripts/generate_docs_for_src.py
## Source: src-old/logic/agents/analysis/tech_debt_core.improvements.md

# Improvements: src/logic/agents/analysis/tech_debt_core.py

Suggested improvements (automatically generated):
- Add unit tests covering core behavior and edge cases.
- Break large modules into smaller, testable components.
- Avoid heavy imports at module import time; import lazily where appropriate.
- Add type hints and explicit return types for public functions.
- Add logging and better error handling for file and IO operations.
- Consider dependency injection for filesystem and environment interactions.

LLM_CONTEXT_END

"""

from __future__ import annotations

# Copyright 2026 PyAgent Authors
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,

"""
TechDebtCore: Core logic for technical debt analysis and management in PyAgent.
Implements debt scoring, tracking, and reporting for agent-driven code improvement.
"""
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Tech debt core.py module.
"""



import ast
from typing import Any

from src.core.base.lifecycle.version import VERSION

try:
    import rust_core as rc

    HAS_RUST = True
except ImportError:
    HAS_RUST = False

__version__ = VERSION


class TechDebtCore:
    """Pure logic for analyzing technical debt from AST.
    Ready for Rust conversion.
    """

    @staticmethod
    def analyze_ast_debt(tree: ast.AST) -> list[dict[str, Any]]:
        """Analyzes an AST tree for technical debt markers.

        Args:
            tree: The pre-parsed AST tree.

        Returns:
            A list of identified issues.

        """
        # Count missing docstrings
        missing_docstrings = 0
        for node in ast.walk(tree):
            if isinstance(node, (ast.FunctionDef, ast.ClassDef, ast.Module)):
                if not ast.get_docstring(node):
                    missing_docstrings += 1

        # Count AST nodes (complexity proxy)
        node_count = sum(1 for _ in ast.walk(tree))

        # Use Rust for issue analysis if available
        if HAS_RUST:
            # Rust function: analyze_tech_debt_rust(node_count, missing_docstrings, todo_count)
            return rc.analyze_tech_debt_rust(node_count, missing_docstrings, 0)

        # Python fallback
        issues = []
        for node in ast.walk(tree):
            if isinstance(node, (ast.FunctionDef, ast.ClassDef, ast.Module)):
                if not ast.get_docstring(node):
                    issues.append(
                        {
                            "type": "Missing Docstring",
                            "name": getattr(node, "name", "Module"),
                            "severity": "Low",
                        }
                    )

        if node_count > 1000:
            issues.append(
                {
                    "type": "High Complexity",
                    "detail": f"Structure contains {node_count} AST nodes.",
                    "severity": "Medium",
                }
            )

        return issues

    @staticmethod
    def identify_hotspots(reports: list[dict[str, Any]], limit: int = 5) -> list[dict[str, Any]]:
        """Sorts and returns major technical debt hotspots."""
        return sorted(reports, key=lambda x: x.get("issue_count", 0), reverse=True)[:limit]
