#!/usr/bin/env python3
"""
LLM_CONTEXT_START

## Source: src-old/observability/errors/error_budget.description.md

# Description: src/observability/errors/error_budget.py

Module docstring (if present):

    Auto-extracted class from agent_errors.py

Top-level members:
- Classes: ErrorBudget

Notes:
- This description was auto-generated by scripts/generate_docs_for_src.py
## Source: src-old/observability/errors/error_budget.improvements.md

# Improvements: src/observability/errors/error_budget.py

Suggested improvements (automatically generated):
- Add unit tests covering core behavior and edge cases.
- Break large modules into smaller, testable components.
- Avoid heavy imports at module import time; import lazily where appropriate.
- Add type hints and explicit return types for public functions.
- Add logging and better error handling for file and IO operations.
- Consider dependency injection for filesystem and environment interactions.

LLM_CONTEXT_END
"""

from __future__ import annotations
# Copyright 2026 PyAgent Authors
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


"""Auto-extracted class from agent_errors.py"""


from dataclasses import dataclass

from src.core.base.lifecycle.version import VERSION

__version__ = VERSION


@dataclass
class ErrorBudget:
    """Error budget tracking for SLO management.

    Attributes:
        budget_name: Name of the error budget.
        total_budget: Total allowed error budget.
        consumed: Amount of budget consumed.
        period_start: Start of the budget period.
        period_end: End of the budget period.
    """

    budget_name: str
    total_budget: float
    consumed: float = 0.0
    period_start: str = ""
    period_end: str = ""
