#!/usr/bin/env python3
"""LLM_CONTEXT_START

## Source: src-old/observability/errors/notification_config.description.md

# Description: src/observability/errors/notification_config.py

Module docstring (if present):

    Auto-extracted class from agent_errors.py

Top-level members:
- Classes: NotificationConfig

Notes:
- This description was auto-generated by scripts/generate_docs_for_src.py
## Source: src-old/observability/errors/notification_config.improvements.md

# Improvements: src/observability/errors/notification_config.py

Suggested improvements (automatically generated):
- Add unit tests covering core behavior and edge cases.
- Break large modules into smaller, testable components.
- Avoid heavy imports at module import time; import lazily where appropriate.
- Add type hints and explicit return types for public functions.
- Add logging and better error handling for file and IO operations.
- Consider dependency injection for filesystem and environment interactions.

LLM_CONTEXT_END

"""

from __future__ import annotations

# Copyright 2026 PyAgent Authors
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


"""Auto-extracted class from agent_errors.py"""


from dataclasses import dataclass

from src.core.base.lifecycle.version import VERSION

from .error_severity import ErrorSeverity
from .notification_channel import NotificationChannel

__version__ = VERSION


@dataclass
class NotificationConfig:
    """Configuration for error notifications.

    Attributes:
        channel: Notification channel type.
        endpoint: Webhook URL or email address.
        min_severity: Minimum severity to notify.
        enabled: Whether notifications are enabled.
        template: Message template.

    """

    channel: NotificationChannel
    endpoint: str
    min_severity: ErrorSeverity = ErrorSeverity.HIGH
    enabled: bool = True
    template: str = "Error: {message} in {file}:{line}"
