#!/usr/bin/env python3
"""LLM_CONTEXT_START

## Source: src-old/observability/errors/timeline_tracker.description.md

# Description: src/observability/errors/timeline_tracker.py

Module docstring (if present):

    Auto-extracted class from agent_errors.py

Top-level members:
- Classes: TimelineTracker

Notes:
- This description was auto-generated by scripts/generate_docs_for_src.py
## Source: src-old/observability/errors/timeline_tracker.improvements.md

# Improvements: src/observability/errors/timeline_tracker.py

Suggested improvements (automatically generated):
- Add unit tests covering core behavior and edge cases.
- Break large modules into smaller, testable components.
- Avoid heavy imports at module import time; import lazily where appropriate.
- Add type hints and explicit return types for public functions.
- Add logging and better error handling for file and IO operations.
- Consider dependency injection for filesystem and environment interactions.

LLM_CONTEXT_END

"""

from __future__ import annotations

# Copyright 2026 PyAgent Authors
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


"""Auto-extracted class from agent_errors.py"""


from datetime import datetime
from typing import Any

from src.core.base.lifecycle.version import VERSION

from .timeline_event import TimelineEvent

__version__ = VERSION


class TimelineTracker:
    """Tracks error events over time.

    Maintains a timeline of error creation, resolution, and recurrence
    events for visualization and analysis.

    Attributes:
        events: List of timeline events.

    """

    def __init__(self) -> None:
        """Initialize the timeline tracker."""
        self.events: list[TimelineEvent] = []

    def record_event(self, error_id: str, event_type: str, details: str = "") -> TimelineEvent:
        """Record a timeline event.

        Args:
            error_id: ID of the associated error.
            event_type: Type of event (created, resolved, recurred).
            details: Additional event details.

        Returns:
            The recorded TimelineEvent.

        """
        event = TimelineEvent(
            timestamp=datetime.now().isoformat(),
            event_type=event_type,
            error_id=error_id,
            details=details,
        )
        self.events.append(event)
        return event

    def get_events_for_error(self, error_id: str) -> list[TimelineEvent]:
        """Get all events for a specific error."""
        return [e for e in self.events if e.error_id == error_id]

    def get_events_in_range(self, start: str, end: str) -> list[TimelineEvent]:
        """Get events within a time range."""
        return [e for e in self.events if start <= e.timestamp <= end]

    def generate_timeline_data(self) -> dict[str, Any]:
        """Generate timeline data for visualization."""
        by_date: dict[str, int] = {}
        for event in self.events:
            date = event.timestamp[:10]  # YYYY - MM - DD
            by_date[date] = by_date.get(date, 0) + 1

        return {
            "total_events": len(self.events),
            "events_by_date": by_date,
            "event_types": list(set(e.event_type for e in self.events)),
        }

    def clear(self) -> None:
        """Clear all timeline events."""
        self.events = []
