# -*- coding: utf-8 -*-
"""Extracted test classes from test_base_agent.py."""

__all__ = [
    "TestAgentComposer",
    "TestAgentCompositionPatterns",
    "TestAgentConfig",
    "TestAgentConfigurationProfiles",
    "TestAgentEventHooks",
    "TestAgentHealthDiagnostics",
    "TestAgentPluginLoading",
    "TestAgentState",
    "TestAgentStatePersistence",
    "TestAuthenticationManager",
    "TestCacheManagement",
    "TestContentBasedResponseCaching",
    "TestContextWindow",
    "TestContextWindowManagement",
    "TestConversationHistory",
    "TestConversationHistoryManagement",
    "TestCustomAuthenticationMethods",
    "TestEventHooks",
    "TestEventType",
    "TestFilePriorityManager",
    "TestHealthCheckResult",
    "TestHealthChecks",
    "TestModelSelection",
    "TestModelSelectionPerAgentType",
    "TestMultimodalInputHandling",
    "TestMultimodalProcessor",
    "TestPluginSystem",
    "TestPostProcessors",
    "TestPromptTemplate",
    "TestPromptTemplates",
    "TestPromptTemplatingSystem",
    "TestPromptVersionManager",
    "TestPromptVersioningAndABTesting",
    "TestRequestBatcher",
    "TestRequestBatchingPerformance",
    "TestResponsePostProcessingHooks",
    "TestResponseQuality",
    "TestResponseQualityScoring",
    "TestResponseQualityScoring_v2",
    "TestSerializationManager",
    "TestSession8Dataclasses",
    "TestSession8Enums",
    "TestStatePersistence",
    "TestTokenBudget",
    "TestTokenBudgetManagement",
]

from .core import *  # noqa: F401, F403
from .performance import *  # noqa: F401, F403
