#!/usr/bin/env python3
# Copyright 2026 PyAgent Authors
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Generate llms-architecture.txt by consolidating docs/architecture content.

This script is intended to provide a stable, deterministic context file that
agents can use as input for reasoning or prompting. It collapses the markdown
files under `docs/architecture/` (excluding `archive/` and `adr/`) into a single
text file that can be consumed by an LLM.

Usage:
    python scripts/generate_llms_architecture.py --output project/llms-architecture.txt

It is safe to run repeatedly; output is deterministic and always rewrites the
same file.
"""

from __future__ import annotations

import argparse
import pathlib


def _discover_architecture_docs(root: pathlib.Path) -> list[pathlib.Path]:
    """Find markdown files under docs/architecture (excluding archive/ and adr/)."""
    base = root / "docs" / "architecture"
    files: list[pathlib.Path] = []

    for path in sorted(base.rglob("*.md")):
        # Skip archive and ADR folders
        if "archive" in path.parts or "adr" in path.parts:
            continue
        if path.name == "Architecture.md":
            # Keep it too (top-level architecture summary)
            pass
        files.append(path)

    return sorted(files)


def _render_file(path: pathlib.Path, repo_root: pathlib.Path) -> str:
    """Render a markdown file with a header that includes its relative path."""
    rel = path.relative_to(repo_root).as_posix()
    content = path.read_text(encoding="utf-8")
    header = f"\n\n---\n# Source: {rel}\n---\n\n"
    return header + content.strip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate llms-architecture.txt from docs/architecture/"
    )
    parser.add_argument(
        "--output",
        type=pathlib.Path,
        default=pathlib.Path("project/llms-architecture.txt"),
        help="Output file path (default: project/llms-architecture.txt)",
    )
    parser.add_argument(
        "--repo-root",
        type=pathlib.Path,
        default=pathlib.Path("."),
        help="Repository root path (default: current working directory)",
    )
    args = parser.parse_args()

    repo_root = args.repo_root.resolve()
    output_path = (repo_root / args.output).resolve()

    docs = _discover_architecture_docs(repo_root)

    parts: list[str] = []
    parts.append("# llms-architecture.txt\n")
    parts.append(
        "This file is generated by scripts/generate_llms_architecture.py from the markdown in docs/architecture/.\n"
    )

    for doc in docs:
        parts.append(_render_file(doc, repo_root))

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(parts), encoding="utf-8")

    print(f"Wrote {output_path} (included {len(docs)} docs)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
