#!/usr/bin/env python3
# Copyright 2026 PyAgent Authors
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""SetupTests.py — scaffold mirror test directories for src/ packages.

Creates a tests/<package>/ directory for each src/ top-level package that
does not already have one, and seeds it with an __init__.py and a
placeholder test file.

Usage:
    python scripts/SetupTests.py [--src src] [--tests tests] [--dry-run]
"""
from __future__ import annotations

import argparse
import os
from pathlib import Path


def _placeholder_test(pkg: str) -> str:
    return (
        f'"""Placeholder tests for {pkg} (auto-generated by SetupTests.py)."""\n\n\n'
        "def test_placeholder():\n"
        '    """Placeholder — replace with real tests."""\n'
        "    assert True\n"
    )


def create_test_structure(src_root: str, tests_root: str, dry_run: bool = False) -> list[str]:
    """Mirror src/ packages under tests/; return list of created paths."""
    src = Path(src_root)
    tests = Path(tests_root)
    created: list[str] = []

    for entry in sorted(src.iterdir()):
        if not entry.is_dir() or entry.name.startswith("_"):
            continue
        mirror = tests / entry.name
        if mirror.exists():
            continue  # already mirrored — skip
        if dry_run:
            created.append(f"[dry-run] would create {mirror}")
            continue
        mirror.mkdir(parents=True, exist_ok=True)
        (mirror / "__init__.py").touch()
        (mirror / f"test_{entry.name}.py").write_text(
            _placeholder_test(entry.name), encoding="utf-8"
        )
        created.append(str(mirror))

    return created


def main() -> None:
    parser = argparse.ArgumentParser(description="Scaffold mirror test directories")
    parser.add_argument("--src", default="src", help="Source root (default: src)")
    parser.add_argument("--tests", default="tests", help="Tests root (default: tests)")
    parser.add_argument("--dry-run", action="store_true", help="Print what would be created")
    args = parser.parse_args()

    created = create_test_structure(args.src, args.tests, dry_run=args.dry_run)
    if created:
        for p in created:
            print(f"  {p}")
        print(f"Created {len(created)} mirror package(s).")
    else:
        print("All src/ packages already mirrored — nothing to do.")


if __name__ == "__main__":
    main()
