#!/usr/bin/env python3
"""LLM_CONTEXT_START

## Source: src-old/observability/reports/archived_report.description.md

# Description: src/observability/reports/archived_report.py

Module docstring (if present):

    Auto-extracted class from generate_agent_reports.py

Top-level members:
- Classes: ArchivedReport

Notes:
- This description was auto-generated by scripts/generate_docs_for_src.py
## Source: src-old/observability/reports/archived_report.improvements.md

# Improvements: src/observability/reports/archived_report.py

Suggested improvements (automatically generated):
- Add unit tests covering core behavior and edge cases.
- Break large modules into smaller, testable components.
- Avoid heavy imports at module import time; import lazily where appropriate.
- Add type hints and explicit return types for public functions.
- Add logging and better error handling for file and IO operations.
- Consider dependency injection for filesystem and environment interactions.

LLM_CONTEXT_END

"""

from __future__ import annotations

# Copyright 2026 PyAgent Authors
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


"""Auto-extracted class from generate_agent_reports.py"""


import time
from dataclasses import dataclass, field
from typing import Any

from src.core.base.lifecycle.version import VERSION

__version__ = VERSION


@dataclass
class ArchivedReport:
    """Archived report with retention info.

    Attributes:
        report_id: Unique report identifier.
        file_path: Original file path.
        content: Report content.
        archived_at: Archive timestamp.
        retention_days: Days to retain.
        metadata: Report metadata.

    """

    report_id: str
    file_path: str
    content: str
    archived_at: float = field(default_factory=time.time)  # type: ignore[assignment]
    retention_days: int = 90
    metadata: dict[str, Any] = field(default_factory=dict)  # type: ignore[assignment]
