#!/usr/bin/env python3
"""LLM_CONTEXT_START

## Source: src-old/observability/reports/code_issue.description.md

# Description: src/observability/reports/code_issue.py

Module docstring (if present):

    Auto-extracted class from generate_agent_reports.py

Top-level members:
- Classes: CodeIssue

Notes:
- This description was auto-generated by scripts/generate_docs_for_src.py
## Source: src-old/observability/reports/code_issue.improvements.md

# Improvements: src/observability/reports/code_issue.py

Suggested improvements (automatically generated):
- Add unit tests covering core behavior and edge cases.
- Break large modules into smaller, testable components.
- Avoid heavy imports at module import time; import lazily where appropriate.
- Add type hints and explicit return types for public functions.
- Add logging and better error handling for file and IO operations.
- Consider dependency injection for filesystem and environment interactions.

LLM_CONTEXT_END

"""

from __future__ import annotations

# Copyright 2026 PyAgent Authors
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


"""Auto-extracted class from generate_agent_reports.py"""


from dataclasses import dataclass

from src.core.base.lifecycle.version import VERSION

from .issue_category import IssueCategory
from .severity_level import SeverityLevel

__version__ = VERSION


@dataclass
class CodeIssue:
    """Represents a code issue or improvement suggestion.

    Attributes:
        message: Issue description.
        category: Issue category.
        severity: Severity level.
        line_number: Line number if applicable.
        file_path: File path if applicable.
        function_name: Function name if applicable.

    """

    message: str
    category: IssueCategory
    severity: SeverityLevel = SeverityLevel.INFO
    line_number: int | None = None
    file_path: str | None = None
    function_name: str | None = None
