#!/usr/bin/env python3
"""
LLM_CONTEXT_START

## Source: src-old/observability/reports/report_subscription.description.md

# Description: src/observability/reports/report_subscription.py

Module docstring (if present):

    Auto-extracted class from generate_agent_reports.py

Top-level members:
- Classes: ReportSubscription

Notes:
- This description was auto-generated by scripts/generate_docs_for_src.py
## Source: src-old/observability/reports/report_subscription.improvements.md

# Improvements: src/observability/reports/report_subscription.py

Suggested improvements (automatically generated):
- Add unit tests covering core behavior and edge cases.
- Break large modules into smaller, testable components.
- Avoid heavy imports at module import time; import lazily where appropriate.
- Add type hints and explicit return types for public functions.
- Add logging and better error handling for file and IO operations.
- Consider dependency injection for filesystem and environment interactions.

LLM_CONTEXT_END
"""

from __future__ import annotations
# Copyright 2026 PyAgent Authors
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


"""Auto-extracted class from generate_agent_reports.py"""


from dataclasses import dataclass, field

from src.core.base.lifecycle.version import VERSION

from .report_type import ReportType
from .subscription_frequency import SubscriptionFrequency

__version__ = VERSION


@dataclass
class ReportSubscription:
    """Subscription for report delivery.
    Attributes:
        subscriber_id: Unique subscriber identifier.
        email: Email address for delivery.
        frequency: Delivery frequency.
        report_types: Types of reports to receive.
        file_patterns: Patterns for files to include.
        enabled: Whether subscription is active.
    """

    subscriber_id: str
    email: str
    frequency: SubscriptionFrequency = SubscriptionFrequency.DAILY
    report_types: list[ReportType] = field(default_factory=list)  # type: ignore[assignment]
    file_patterns: list[str] = field(default_factory=list)  # type: ignore[assignment]
    enabled: bool = True
