#!/usr/bin/env python3
"""
LLM_CONTEXT_START

## Source: src-old/observability/reports/report_validator.description.md

# Description: src/observability/reports/report_validator.py

Module docstring (if present):

    Validator for report data integrity.
    (Facade for src.core.base.common.validation_core)

Top-level members:
- Classes: ReportValidator

Notes:
- This description was auto-generated by scripts/generate_docs_for_src.py
## Source: src-old/observability/reports/report_validator.improvements.md

# Improvements: src/observability/reports/report_validator.py

Suggested improvements (automatically generated):
- Add unit tests covering core behavior and edge cases.
- Break large modules into smaller, testable components.
- Avoid heavy imports at module import time; import lazily where appropriate.
- Add type hints and explicit return types for public functions.
- Add logging and better error handling for file and IO operations.
- Consider dependency injection for filesystem and environment interactions.

LLM_CONTEXT_END
"""

from __future__ import annotations
# Copyright 2026 PyAgent Authors
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Validator for report data integrity.
(Facade for src.core.base.common.validation_core)
"""


import hashlib
from typing import Any

from src.core.base.common.validation_core import ValidationCore

from .validation_result import ValidationResult


class ReportValidator(ValidationCore):
    """Facade for ValidationCore specialized for reports."""

    def validate_report(self, report_data: dict[str, Any]) -> list[str]:
        """Validates report structure."""
        content = report_data.get("summary", "")
        errors = []
        if not content or not content.strip().startswith("# "):
            errors.append("Missing main heading")
        return errors

    def validate(self, content: str, rule_name: str | None = None) -> ValidationResult:
        """Main entry point for report validation."""
        del rule_name  # Unused in this facade
        errors = self.validate_report({"summary": content, "agent_name": "unknown", "timestamp": 0})

        warnings = []
        if "]()" in content:
            warnings.append("Contains empty link targets")

        checksum = hashlib.sha256(content.encode()).hexdigest()[:16]

        return ValidationResult(
            valid=len(errors) == 0,
            errors=errors,
            warnings=warnings,
            checksum=checksum
        )

    def verify_hash(self, content: str, expected: str) -> bool:
        """Verifies content matches expected hash."""
        actual = hashlib.sha256(content.encode()).hexdigest()[:16]
        return actual == expected

    def verify_checksum(self, content: str, expected: str) -> bool:
        """Alias for verify_hash to match test expectations."""
        return self.verify_hash(content, expected)
