#!/usr/bin/env python3
"""
LLM_CONTEXT_START

## Source: src-old/observability/reports/swarm_topology_reporter.description.md

# Description: src/observability/reports/swarm_topology_reporter.py

Module docstring (if present):

    Swarm topology reporter.py module.

Top-level members:
- Classes: SwarmTopologyReporter

Notes:
- This description was auto-generated by scripts/generate_docs_for_src.py
## Source: src-old/observability/reports/swarm_topology_reporter.improvements.md

# Improvements: src/observability/reports/swarm_topology_reporter.py

Suggested improvements (automatically generated):
- Add unit tests covering core behavior and edge cases.
- Break large modules into smaller, testable components.
- Avoid heavy imports at module import time; import lazily where appropriate.
- Add type hints and explicit return types for public functions.
- Add logging and better error handling for file and IO operations.
- Consider dependency injection for filesystem and environment interactions.

LLM_CONTEXT_END
"""

from __future__ import annotations
# Copyright 2026 PyAgent Authors
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Swarm topology reporter.py module.
"""



import json
import logging
from pathlib import Path
from typing import Any

from src.core.base.lifecycle.version import VERSION

__version__ = VERSION


class SwarmTopologyReporter:
    """
    Generates D3.js compatible topology data for 3D Swarm Viewer.
    Captures node relationships, trust scores, and communication latency.
    """

    def __init__(self, output_path: str = "data/logs/topology.json") -> None:
        self.output_path = Path(output_path)
        self.nodes: list[Any] = []
        self.links: list[Any] = []

    def record_node(
        self,
        node_id: str,
        group: str = "general",
        metadata: dict[str, Any] | None = None,
    ) -> None:
        self.nodes.append({"id": node_id, "group": group, "meta": metadata or {}})

    def record_link(self, source: str, target: str, strength: float = 1.0, type: str = "coord") -> None:
        self.links.append({"source": source, "target": target, "value": strength, "type": type})

    def export(self) -> None:
        data = {
            "nodes": self.nodes,
            "links": self.links,
            "timestamp": "2026-01-11T18:00:00",
        }
        self.output_path.parent.mkdir(parents=True, exist_ok=True)
        with open(self.output_path, 'w', encoding='utf-8') as f:
            json.dump(data, f, indent=2)
        logging.info(f"Topology exported to {self.output_path}")


# Integration hook in FleetManager would call this.
