#!/usr/bin/env python3
# Copyright 2026 PyAgent Authors
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""LLM_CONTEXT_START

## Source: src-old/interface/slash_commands/commands/chat_decorator.description.md

# Description: src/interface/slash_commands/commands/chat_decorator.py

Module docstring (if present):

    Chat decorator commands for formatting conversations with safe HTML/CSS.

    Commands:
        /chat - Format a full conversation exchange
        /human - Decorate a human/user prompt
        /ai - Decorate an AI/assistant response
        /system - Decorate a system message
        /code - Decorate a code block with syntax highlighting style
        /thinking - Decorate AI thinking/reasoning block

Top-level members:
- Functions: _clean_style, _escape_html, _format_message, _format_conversation, cmd_human, cmd_ai, cmd_system_message, cmd_thinking, cmd_codeblock, cmd_chat

Notes:
- This description was auto-generated by scripts/generate_docs_for_src.py
## Source: src-old/interface/slash_commands/commands/chat_decorator.improvements.md

# Improvements: src/interface/slash_commands/commands/chat_decorator.py

Suggested improvements (automatically generated):
- Add unit tests covering core behavior and edge cases.
- Break large modules into smaller, testable components.
- Avoid heavy imports at module import time; import lazily where appropriate.
- Add type hints and explicit return types for public functions.
- Add logging and better error handling for file and IO operations.
- Consider dependency injection for filesystem and environment interactions.

LLM_CONTEXT_END

"""

"""
Chat decorator commands for formatting conversations with safe HTML/CSS.

Commands:
    /chat - Format a full conversation exchange
    /human - Decorate a human/user prompt
    /ai - Decorate an AI/assistant response
    /system - Decorate a system message
    /code - Decorate a code block with syntax highlighting style
    /thinking - Decorate AI thinking/reasoning block
"""
import html
import re
from typing import Literal

from ..core import CommandContext, CommandResult
from ..registry import register

# Safe inline CSS styles (no external resources, no scripts)
STYLES = {
    "container": """
    """
