use pyo3::prelude::*;

pub mod attention;
pub mod cache;
pub mod distributed;
pub mod engine;
pub mod hashing;
pub mod input;
pub mod layers;
pub mod lora;
pub mod memory;
pub mod metrics;
pub mod moe;
pub mod ngram;
pub mod platform;
pub mod pooling;
pub mod queue;
pub mod registry;
pub mod sampling;
pub mod scheduler;

pub mod stats;
pub mod tokenizer;
pub mod tools;
pub mod verification;
pub mod weights;

use crate::inference::attention::*;
use crate::inference::cache::*;
use crate::inference::distributed::*;
use crate::inference::engine::*;
use crate::inference::hashing::*;
use crate::inference::input::*;
use crate::inference::layers::*;
use crate::inference::lora::*;
use crate::inference::memory::*;
use crate::inference::metrics::*;
use crate::inference::moe::*;
use crate::inference::ngram::*;
use crate::inference::platform::*;
use crate::inference::pooling::*;
use crate::inference::queue::*;
use crate::inference::registry::*;
use crate::inference::sampling::*;
use crate::inference::scheduler::*;
use crate::inference::stats::*;
use crate::inference::tokenizer::*;
use crate::inference::tools::*;
use crate::inference::verification::*;
use crate::inference::weights::*;

pub fn register(m: &Bound<'_, PyModule>) -> PyResult<()> {
    m.add_function(wrap_pyfunction!(apply_ia3_scaling_rust, m)?)?;
    m.add_function(wrap_pyfunction!(adaptive_top_k_rust, m)?)?;
    m.add_function(wrap_pyfunction!(apply_lora_rust, m)?)?;
    m.add_function(wrap_pyfunction!(count_tokens_rust, m)?)?;
    m.add_function(wrap_pyfunction!(advanced_ngram_propose_rust, m)?)?; // Restored
    m.add_function(wrap_pyfunction!(aggregate_iteration_stats_rust, m)?)?;
    m.add_function(wrap_pyfunction!(aggregate_expert_loads_rust, m)?)?;
    m.add_function(wrap_pyfunction!(aggregate_stats_window_rust, m)?)?;
    m.add_function(wrap_pyfunction!(aggregate_token_metrics_rust, m)?)?;
    m.add_function(wrap_pyfunction!(all_reduce_sum_rust, m)?)?;
    m.add_function(wrap_pyfunction!(analyze_shape_patterns_rust, m)?)?;
    m.add_function(wrap_pyfunction!(analyze_trend_rust, m)?)?;
    m.add_function(wrap_pyfunction!(apply_bad_words_mask_rust, m)?)?;
    m.add_function(wrap_pyfunction!(apply_grammar_mask_rust, m)?)?;
    m.add_function(wrap_pyfunction!(apply_min_p_rust, m)?)?;
    m.add_function(wrap_pyfunction!(apply_temperature_schedule_rust, m)?)?;
    m.add_function(wrap_pyfunction!(apply_top_k_rust, m)?)?;
    m.add_function(wrap_pyfunction!(apply_top_p_rust, m)?)?;
    m.add_function(wrap_pyfunction!(apply_typical_sampling_rust, m)?)?;
    m.add_function(wrap_pyfunction!(apply_whitelist_mask_rust, m)?)?;
    m.add_function(wrap_pyfunction!(arc_adaptation_delta_rust, m)?)?;
    m.add_function(wrap_pyfunction!(arc_cache_balance_rust, m)?)?; // Restored
    m.add_function(wrap_pyfunction!(arc_cache_priority_rust, m)?)?;
    m.add_function(wrap_pyfunction!(architecture_fingerprint_rust, m)?)?;
    m.add_function(wrap_pyfunction!(async_output_merge_rust, m)?)?;
    m.add_function(wrap_pyfunction!(attention_dispatch_rust, m)?)?;
    m.add_function(wrap_pyfunction!(attention_pool_rust, m)?)?; 
    m.add_function(wrap_pyfunction!(attention_weighted_pool_rust, m)?)?;
    m.add_function(wrap_pyfunction!(bad_words_match_ngram_rust, m)?)?;
    m.add_function(wrap_pyfunction!(bad_words_prefix_check_rust, m)?)?;
    m.add_function(wrap_pyfunction!(bad_words_trie_build_rust, m)?)?;
    m.add_function(wrap_pyfunction!(batch_apply_penalties_rust, m)?)?;
    m.add_function(wrap_pyfunction!(batch_block_hash_rust, m)?)?;
    m.add_function(wrap_pyfunction!(compute_block_hashes_batched_rust, m)?)?; // Restored
    m.add_function(wrap_pyfunction!(batch_descriptor_key_rust, m)?)?; 
    m.add_function(wrap_pyfunction!(batch_estimate_tokens_rust, m)?)?;
    m.add_function(wrap_pyfunction!(batch_fill_bitmask_rust, m)?)?;
    m.add_function(wrap_pyfunction!(batch_grammar_mask_rust, m)?)?;
    m.add_function(wrap_pyfunction!(batch_logprobs_rust, m)?)?;
    m.add_function(wrap_pyfunction!(batch_topk_topp_sample_rust, m)?)?;
    m.add_function(wrap_pyfunction!(batch_update_indices_rust, m)?)?;
    m.add_function(wrap_pyfunction!(batch_write_indices_rust, m)?)?;
    m.add_function(wrap_pyfunction!(blake3_hash_rust, m)?)?;
    m.add_function(wrap_pyfunction!(compute_balanced_packing_rust, m)?)?;
    m.add_function(wrap_pyfunction!(block_hash_compute_rust, m)?)?; 
    m.add_function(wrap_pyfunction!(compute_block_hash_rust, m)?)?; 
    m.add_function(wrap_pyfunction!(compute_block_hashes_rust, m)?)?; 
    m.add_function(wrap_pyfunction!(block_pool_evict_lru_rust, m)?)?;
    m.add_function(wrap_pyfunction!(block_table_lookup_rust, m)?)?;
    m.add_function(wrap_pyfunction!(block_table_slot_mapping_rust, m)?)?;
    m.add_function(wrap_pyfunction!(blocks_to_free_rust, m)?)?;
    m.add_function(wrap_pyfunction!(bpe_encode_fast_rust, m)?)?;
    m.add_function(wrap_pyfunction!(build_ngram_index_rust, m)?)?;
    m.add_function(wrap_pyfunction!(build_speculation_tree_rust, m)?)?;
    m.add_function(wrap_pyfunction!(build_suffix_array_rust, m)?)?; 
    m.add_function(wrap_pyfunction!(cache_hit_score_rust, m)?)?;
    m.add_function(wrap_pyfunction!(cache_observe_rust, m)?)?;
    m.add_function(wrap_pyfunction!(rank_completions_rust, m)?)?; // Restored
    m.add_function(wrap_pyfunction!(compute_diversity_penalty_rust, m)?)?; // Restored
    m.add_function(wrap_pyfunction!(calculate_blocks_needed_rust, m)?)?;
    m.add_function(wrap_pyfunction!(calculate_memory_pressure_rust, m)?)?;
    m.add_function(wrap_pyfunction!(calculate_throughput_rust, m)?)?;
    m.add_function(wrap_pyfunction!(causal_conv1d_update_rust, m)?)?;
    m.add_function(wrap_pyfunction!(check_capability_rust, m)?)?;
    m.add_function(wrap_pyfunction!(chunk_boundaries_rust, m)?)?;
    m.add_function(wrap_pyfunction!(classify_token_context_rust, m)?)?;
    m.add_function(wrap_pyfunction!(cls_pool_rust, m)?)?; 
    m.add_function(wrap_pyfunction!(coalesce_writes_rust, m)?)?;
    m.add_function(wrap_pyfunction!(validate_chat_messages_rust, m)?)?; // Ensure this is registered
    m.add_function(wrap_pyfunction!(estimate_tokens_from_messages_rust, m)?)?; // Renamed from estimate_tokens_rust
    m.add_function(wrap_pyfunction!(compute_arc_target_rust, m)?)?;
    m.add_function(wrap_pyfunction!(compute_moe_balanced_packing_rust, m)?)?;
    m.add_function(wrap_pyfunction!(compute_block_eviction_order_rust, m)?)?;
    m.add_function(wrap_pyfunction!(compute_cache_hit_rate_rust, m)?)?;
    m.add_function(wrap_pyfunction!(compute_deadline_priorities_rust, m)?)?;
    m.add_function(wrap_pyfunction!(compute_entropy_rust, m)?)?;
    m.add_function(wrap_pyfunction!(compute_expert_replication_rust, m)?)?;
    m.add_function(wrap_pyfunction!(compute_log_to_phy_rust, m)?)?;
    m.add_function(wrap_pyfunction!(compute_fair_schedule_rust, m)?)?;
    m.add_function(wrap_pyfunction!(compute_idx_mapping_rust, m)?)?;
    m.add_function(wrap_pyfunction!(compute_load_imbalance_rust, m)?)?;
    m.add_function(wrap_pyfunction!(compute_lru_eviction_rust, m)?)?;
    m.add_function(wrap_pyfunction!(compute_optimal_graph_sizes_rust, m)?)?;
    m.add_function(wrap_pyfunction!(compute_padded_buffer_size_rust, m)?)?;
    m.add_function(wrap_pyfunction!(compute_percentiles_rust, m)?)?;
    m.add_function(wrap_pyfunction!(compute_perplexity_rust, m)?)?;
    m.add_function(wrap_pyfunction!(compute_shard_assignment_rust, m)?)?;
    m.add_function(wrap_pyfunction!(compute_ubatch_slices_rust, m)?)?;
    m.add_function(wrap_pyfunction!(constraint_hash_rust, m)?)?;
    m.add_function(wrap_pyfunction!(counter_increment_rust, m)?)?;
    m.add_function(wrap_pyfunction!(cudagraph_key_hash_rust, m)?)?;
    m.add_function(wrap_pyfunction!(cudagraph_stats_compute_rust, m)?)?; 
    m.add_function(wrap_pyfunction!(dcp_group_coordinate_rust, m)?)?;
    m.add_function(wrap_pyfunction!(deadline_check_rust, m)?)?; 
    m.add_function(wrap_pyfunction!(defragment_blocks_rust, m)?)?;
    m.add_function(wrap_pyfunction!(detect_anomalies_rust, m)?)?;
    m.add_function(wrap_pyfunction!(detect_architecture_rust, m)?)?;
    m.add_function(wrap_pyfunction!(detect_chat_template_rust, m)?)?;
    m.add_function(wrap_pyfunction!(detect_tool_format_rust, m)?)?;
    m.add_function(wrap_pyfunction!(dispatch_decision_rust, m)?)?;
    m.add_function(wrap_pyfunction!(dp_rank_coordinate_rust, m)?)?;
    m.add_function(wrap_pyfunction!(dynamic_ntk_alpha_rust, m)?)?;
    m.add_function(wrap_pyfunction!(eagle_extrapolate_hidden_rust, m)?)?;
    m.add_function(wrap_pyfunction!(eagle_prepare_inputs_padded_rust, m)?)?;
    m.add_function(wrap_pyfunction!(eagle_top_k_candidates_rust, m)?)?;
    m.add_function(wrap_pyfunction!(eagle_tree_expand_rust, m)?)?;
    m.add_function(wrap_pyfunction!(eagle_verify_accept_rust, m)?)?;
    m.add_function(wrap_pyfunction!(ema_update_rust, m)?)?;
    m.add_function(wrap_pyfunction!(encode_sse_event_rust, m)?)?;
    m.add_function(wrap_pyfunction!(encoder_cache_lru_evict_rust, m)?)?; 
    m.add_function(wrap_pyfunction!(encoder_content_hash_rust, m)?)?; 
    m.add_function(wrap_pyfunction!(estimate_memory_footprint_rust, m)?)?;
    m.add_function(wrap_pyfunction!(estimate_vram_bytes_rust, m)?)?;
    m.add_function(wrap_pyfunction!(event_query_rust, m)?)?; 
    m.add_function(wrap_pyfunction!(eviction_breakdown_rust, m)?)?;
    m.add_function(wrap_pyfunction!(expand_idx_mapping_rust, m)?)?;
    m.add_function(wrap_pyfunction!(extract_accepted_path_rust, m)?)?;
    m.add_function(wrap_pyfunction!(extract_json_positions_rust, m)?)?;
    m.add_function(wrap_pyfunction!(extract_thinking_blocks_rust, m)?)?;
    m.add_function(wrap_pyfunction!(extract_top_k_batch_rust, m)?)?;
    m.add_function(wrap_pyfunction!(extract_top_k_logprobs_rust, m)?)?;
    m.add_function(wrap_pyfunction!(fast_token_count_rust, m)?)?;
    m.add_function(wrap_pyfunction!(fill_token_bitmask_rust, m)?)?;
    m.add_function(wrap_pyfunction!(find_continuations_rust, m)?)?; 
    m.add_function(wrap_pyfunction!(find_placeholders_rust, m)?)?; 
    m.add_function(wrap_pyfunction!(find_prefix_match_rust, m)?)?;
    m.add_function(wrap_pyfunction!(fused_packkv_attention_rust, m)?)?;
    m.add_function(wrap_pyfunction!(future_batch_complete_rust, m)?)?;
    m.add_function(wrap_pyfunction!(gauge_update_rust, m)?)?;
    m.add_function(wrap_pyfunction!(generate_cache_salt_rust, m)?)?;
    m.add_function(wrap_pyfunction!(generate_sample_seeds_rust, m)?)?;
    m.add_function(wrap_pyfunction!(gpu_memory_snapshot_rust, m)?)?;
    m.add_function(wrap_pyfunction!(grammar_cache_key_rust, m)?)?;
    m.add_function(wrap_pyfunction!(gumbel_noise_rust, m)?)?;
    m.add_function(wrap_pyfunction!(hash_conversation_context_rust, m)?)?; 
    m.add_function(wrap_pyfunction!(histogram_observe_rust, m)?)?;
    m.add_function(wrap_pyfunction!(json_schema_fsm_rust, m)?)?;
    m.add_function(wrap_pyfunction!(json_schema_paths_rust, m)?)?;
    m.add_function(wrap_pyfunction!(kv_cache_metrics_aggregate_rust, m)?)?;
    m.add_function(wrap_pyfunction!(kv_connector_score_rust, m)?)?; 
    m.add_function(wrap_pyfunction!(kv_metrics_aggregate_rust, m)?)?; 
    m.add_function(wrap_pyfunction!(kv_transfer_metadata_rust, m)?)?;
    m.add_function(wrap_pyfunction!(last_token_pool_rust, m)?)?; 
    m.add_function(wrap_pyfunction!(lfu_evict_rust, m)?)?;
    m.add_function(wrap_pyfunction!(linearize_chat_rust, m)?)?;
    m.add_function(wrap_pyfunction!(log_softmax_stable_rust, m)?)?;
    m.add_function(wrap_pyfunction!(logit_bias_apply_rust, m)?)?;
    m.add_function(wrap_pyfunction!(logprobs_to_lists_rust, m)?)?;
    m.add_function(wrap_pyfunction!(lora_adapter_hash_rust, m)?)?;
    m.add_function(wrap_pyfunction!(lora_adapter_lru_rust, m)?)?;
    m.add_function(wrap_pyfunction!(lora_delta_compute_rust, m)?)?;
    m.add_function(wrap_pyfunction!(lora_latency_percentile_rust, m)?)?;
    m.add_function(wrap_pyfunction!(lora_scaling_rust, m)?)?;
    m.add_function(wrap_pyfunction!(lora_stats_update_rust, m)?)?;
    m.add_function(wrap_pyfunction!(lru_evict_candidates_rust, m)?)?;
    m.add_function(wrap_pyfunction!(lru_evict_rust, m)?)?;
    m.add_function(wrap_pyfunction!(lru_eviction_priority_rust, m)?)?;
    m.add_function(wrap_pyfunction!(matryoshka_truncate_rust, m)?)?; 
    m.add_function(wrap_pyfunction!(mean_pool_rust, m)?)?; 
    m.add_function(wrap_pyfunction!(memory_pressure_rust, m)?)?;
    m.add_function(wrap_pyfunction!(min_p_threshold_rust, m)?)?;
    m.add_function(wrap_pyfunction!(mirostat_sample_rust, m)?)?;
    m.add_function(wrap_pyfunction!(mla_compress_kv_rust, m)?)?;
    m.add_function(wrap_pyfunction!(mla_head_mapping_rust, m)?)?;
    m.add_function(wrap_pyfunction!(moe_aux_loss_rust, m)?)?;
    m.add_function(wrap_pyfunction!(moe_expert_choice_route_rust, m)?)?;
    m.add_function(wrap_pyfunction!(moe_topk_route_rust, m)?)?;
    m.add_function(wrap_pyfunction!(mrope_section_indices_rust, m)?)?;
    m.add_function(wrap_pyfunction!(ngram_find_match_rust, m)?)?;
    m.add_function(wrap_pyfunction!(ngram_fuzzy_match_rust, m)?)?;
    m.add_function(wrap_pyfunction!(ngram_match_rust, m)?)?;
    m.add_function(wrap_pyfunction!(ngram_propose_rust, m)?)?; 
    m.add_function(wrap_pyfunction!(optimize_block_copy_order_rust, m)?)?;
    m.add_function(wrap_pyfunction!(p2c_select_worker_rust, m)?)?;
    m.add_function(wrap_pyfunction!(pack_tensor_metadata_rust, m)?)?;
    m.add_function(wrap_pyfunction!(parallel_scan_rust, m)?)?;
    m.add_function(wrap_pyfunction!(parse_mcp_tool_call_rust, m)?)?;
    m.add_function(wrap_pyfunction!(parse_response_json_rust, m)?)?;
    m.add_function(wrap_pyfunction!(parse_sse_event_rust, m)?)?;
    m.add_function(wrap_pyfunction!(parse_tool_arguments_rust, m)?)?;
    m.add_function(wrap_pyfunction!(parse_tool_calls_rust, m)?)?;
    m.add_function(wrap_pyfunction!(perceptual_hash_distance_rust, m)?)?;
    m.add_function(wrap_pyfunction!(persistent_gemm_tile_rust, m)?)?; 
    m.add_function(wrap_pyfunction!(platform_fingerprint_rust, m)?)?;
    m.add_function(wrap_pyfunction!(pool_sequences_rust, m)?)?;
    m.add_function(wrap_pyfunction!(pooling_cursor_advance_rust, m)?)?;
    m.add_function(wrap_pyfunction!(preemption_score_rust, m)?)?; 
    m.add_function(wrap_pyfunction!(prefix_tree_lookup_rust, m)?)?; 
    m.add_function(wrap_pyfunction!(prepare_positions_rust, m)?)?;
    m.add_function(wrap_pyfunction!(priority_heap_ops_rust, m)?)?;
    m.add_function(wrap_pyfunction!(prompt_lookup_propose_rust, m)?)?;
    m.add_function(wrap_pyfunction!(rank_assignment_rust, m)?)?; 
    // m.add_function(wrap_pyfunction!(rank_completions_rust, m)?)?; // Missing
    m.add_function(wrap_pyfunction!(regex_dfa_transition_rust, m)?)?;
    m.add_function(wrap_pyfunction!(regex_to_fsm_rust, m)?)?;
    m.add_function(wrap_pyfunction!(rejection_sample_verify_rust, m)?)?;
    m.add_function(wrap_pyfunction!(render_simple_template_rust, m)?)?;
    m.add_function(wrap_pyfunction!(rotary_embedding_kernel_rust, m)?)?;
    m.add_function(wrap_pyfunction!(silu_activation_rust, m)?)?;
    m.add_function(wrap_pyfunction!(sliding_window_hit_rate_rust, m)?)?;
    m.add_function(wrap_pyfunction!(sliding_window_stats_rust, m)?)?;
    m.add_function(wrap_pyfunction!(soft_moe_route_rust, m)?)?;
    m.add_function(wrap_pyfunction!(softmax_stable_rust, m)?)?;
    m.add_function(wrap_pyfunction!(sort_requests_by_priority_rust, m)?)?;
    m.add_function(wrap_pyfunction!(sparse_logprobs_store_rust, m)?)?;
    m.add_function(wrap_pyfunction!(spec_decode_build_cu_indices_rust, m)?)?;
    m.add_function(wrap_pyfunction!(spec_decode_build_logits_indices_rust, m)?)?;
    m.add_function(wrap_pyfunction!(spec_decode_verify_rejection_rust, m)?)?;
    m.add_function(wrap_pyfunction!(speculation_stats_rust, m)?)?;
    m.add_function(wrap_pyfunction!(speculation_tree_parse_rust, m)?)?;
    m.add_function(wrap_pyfunction!(ssm_discretize_rust, m)?)?;
    m.add_function(wrap_pyfunction!(ssm_step_rust, m)?)?;
    m.add_function(wrap_pyfunction!(step_counter_sync_rust, m)?)?;
    m.add_function(wrap_pyfunction!(stream_sync_rust, m)?)?;
    m.add_function(wrap_pyfunction!(structural_tag_parse_rust, m)?)?;
    m.add_function(wrap_pyfunction!(suffix_search_rust, m)?)?; 
    m.add_function(wrap_pyfunction!(task_priority_sort_rust, m)?)?;
    m.add_function(wrap_pyfunction!(template_extract_variables_rust, m)?)?;
    m.add_function(wrap_pyfunction!(tensorizer_checksum_rust, m)?)?;
    m.add_function(wrap_pyfunction!(token_budget_check_rust, m)?)?; 
    m.add_function(wrap_pyfunction!(tokenizer_cache_key_rust, m)?)?;
    m.add_function(wrap_pyfunction!(track_compile_event_rust, m)?)?; 
    m.add_function(wrap_pyfunction!(tree_verification_paths_rust, m)?)?;
    m.add_function(wrap_pyfunction!(triton_attention_dispatch_rust, m)?)?;
    m.add_function(wrap_pyfunction!(truncate_tokens_rust, m)?)?;
    m.add_function(wrap_pyfunction!(uva_copy_rust, m)?)?;
    m.add_function(wrap_pyfunction!(validate_chat_messages_rust, m)?)?;
    m.add_function(wrap_pyfunction!(validate_json_schema_fast_rust, m)?)?; 
    m.add_function(wrap_pyfunction!(validate_mcp_schema_rust, m)?)?;
    m.add_function(wrap_pyfunction!(validate_partial_json_rust, m)?)?;
    m.add_function(wrap_pyfunction!(validate_shard_shapes_rust, m)?)?;
    m.add_function(wrap_pyfunction!(validate_token_sequence_rust, m)?)?;
    m.add_function(wrap_pyfunction!(validate_weight_shapes_rust, m)?)?;
    m.add_function(wrap_pyfunction!(verify_draft_probabilistic_rust, m)?)?;
    m.add_function(wrap_pyfunction!(verify_draft_tokens_batch_rust, m)?)?;
    m.add_function(wrap_pyfunction!(verify_draft_tokens_rust, m)?)?;
    m.add_function(wrap_pyfunction!(verify_speculation_tree_rust, m)?)?;
    m.add_function(wrap_pyfunction!(warmup_sizes_rust, m)?)?; 
    m.add_function(wrap_pyfunction!(wave_id_barrier_rust, m)?)?;
    m.add_function(wrap_pyfunction!(weight_hash_compute_rust, m)?)?;
    m.add_function(wrap_pyfunction!(worker_health_check_rust, m)?)?;
    m.add_function(wrap_pyfunction!(xgrammar_bitmask_fill_rust, m)?)?;
    m.add_function(wrap_pyfunction!(compute_arc_target_size_rust, m)?)?;
    m.add_function(wrap_pyfunction!(multi_modal_hash_rust, m)?)?;
    m.add_function(wrap_pyfunction!(identify_blocks_to_evict_rust, m)?)?;
    m.add_function(wrap_pyfunction!(truncate_chat_history_rust, m)?)?;
    m.add_function(wrap_pyfunction!(pad_input_ids_rust, m)?)?;
    Ok(())
}

