pub mod hash;
pub mod math;
pub mod text;
pub mod search;
pub mod sim;
pub mod json;
pub mod fs;
pub mod system;
pub mod metrics;
pub mod tensor;
pub mod validation;

// Re-export everything to maintain flat access if needed by lib.rs
// pub use hash::*;
// pub use math::*;
// pub use text::*;
// pub use search::*;
// pub use sim::*;
// pub use json::*;
// pub use fs::*;
// pub use system::*;
// pub use metrics::*;
// pub use tensor::*;
// pub use validation::*;

pub fn register(m: &pyo3::Bound<'_, pyo3::prelude::PyModule>) -> pyo3::PyResult<()> {
    use pyo3::prelude::*;
    m.add_function(wrap_pyfunction!(hash::bulk_hash_files_rust, m)?)?;
    m.add_function(wrap_pyfunction!(sim::apply_latency_spike, m)?)?;
    m.add_function(wrap_pyfunction!(tensor::apply_repetition_penalty_rust, m)?)?;
    m.add_function(wrap_pyfunction!(tensor::apply_temperature_rust, m)?)?;
    m.add_function(wrap_pyfunction!(tensor::apply_top_k_rust, m)?)?;
    m.add_function(wrap_pyfunction!(math::atomic_counter_add_rust, m)?)?;
    m.add_function(wrap_pyfunction!(math::batch_cdiv_rust, m)?)?;
    m.add_function(wrap_pyfunction!(math::batch_next_power_of_2_rust, m)?)?;
    m.add_function(wrap_pyfunction!(metrics::cache_hit_ratio_rust, m)?)?;
    m.add_function(wrap_pyfunction!(hash::calculate_interaction_shard_md5, m)?)?;
    m.add_function(wrap_pyfunction!(metrics::calculate_metrics_rust, m)?)?;
    m.add_function(wrap_pyfunction!(sim::calculate_stochastic_failures, m)?)?;
    m.add_function(wrap_pyfunction!(math::cdiv_rust, m)?)?;
    m.add_function(wrap_pyfunction!(text::compress_python_regex, m)?)?;
    m.add_function(wrap_pyfunction!(tensor::compute_logits_mask_rust, m)?)?;
    m.add_function(wrap_pyfunction!(text::dedupe_log_messages_rust, m)?)?;
    m.add_function(wrap_pyfunction!(fs::deep_clean_pycache_rust, m)?)?;
    m.add_function(wrap_pyfunction!(system::detect_cloud_provider_rust, m)?)?;
    m.add_function(wrap_pyfunction!(tensor::encode_slice_rust, m)?)?;
    m.add_function(wrap_pyfunction!(text::ensure_safety_flags_rust, m)?)?;
    m.add_function(wrap_pyfunction!(text::to_snake_case_rust, m)?)?;
    m.add_function(wrap_pyfunction!(text::estimate_tokens_rust, m)?)?; // Restored
    m.add_function(wrap_pyfunction!(math::evaluate_formula, m)?)?;
    m.add_function(wrap_pyfunction!(json::extract_json_tool_calls_rust, m)?)?;
    m.add_function(wrap_pyfunction!(hash::fast_cache_hash_rust, m)?)?;
    m.add_function(wrap_pyfunction!(tensor::search_vector_rust, m)?)?;
    m.add_function(wrap_pyfunction!(hash::fast_hash, m)?)?;
    m.add_function(wrap_pyfunction!(tensor::flat_logprobs_append_rust, m)?)?;
    m.add_function(wrap_pyfunction!(system::flatten_env_vars, m)?)?;
    m.add_function(wrap_pyfunction!(text::format_progress_bar, m)?)?;
    m.add_function(wrap_pyfunction!(text::format_results_block, m)?)?;
    m.add_function(wrap_pyfunction!(system::generate_openapi_spec, m)?)?;
    m.add_function(wrap_pyfunction!(json::json_count_leaves_rust, m)?)?;
    m.add_function(wrap_pyfunction!(json::json_depth_rust, m)?)?;
    m.add_function(wrap_pyfunction!(json::json_flatten_rust, m)?)?;
    m.add_function(wrap_pyfunction!(json::json_get_path_rust, m)?)?;
    m.add_function(wrap_pyfunction!(json::json_iter_leaves_rust, m)?)?;
    m.add_function(wrap_pyfunction!(json::json_validate_leaves_rust, m)?)?;
    m.add_function(wrap_pyfunction!(tensor::msgpack_encode_tensor_meta_rust, m)?)?;
    m.add_function(wrap_pyfunction!(math::next_power_of_2_rust, m)?)?;
    m.add_function(wrap_pyfunction!(system::parse_adb_devices_rust, m)?)?;
    m.add_function(wrap_pyfunction!(search::parse_bing_results, m)?)?;
    m.add_function(wrap_pyfunction!(search::parse_ddg_results, m)?)?;
    m.add_function(wrap_pyfunction!(search::parse_google_results, m)?)?;
    m.add_function(wrap_pyfunction!(text::parse_xml_tool_call_rust, m)?)?;
    m.add_function(wrap_pyfunction!(math::prev_power_of_2_rust, m)?)?;
    m.add_function(wrap_pyfunction!(fs::prune_directory_rust, m)?)?;
    m.add_function(wrap_pyfunction!(math::round_down_rust, m)?)?;
    m.add_function(wrap_pyfunction!(math::round_up_rust, m)?)?;
    m.add_function(wrap_pyfunction!(sim::score_tool_relevance, m)?)?;
    m.add_function(wrap_pyfunction!(metrics::structured_counter_diff_rust, m)?)?;
    m.add_function(wrap_pyfunction!(text::summarize_markdown, m)?)?;
    m.add_function(wrap_pyfunction!(validation::validate_prompt_rust, m)?)?;
    m.add_function(wrap_pyfunction!(tensor::validate_tensor_shape_rust, m)?)?;
    m.add_function(wrap_pyfunction!(hash::xxhash_rust, m)?)?;
    m.add_function(wrap_pyfunction!(text::find_literal_rust, m)?)?;
    m.add_function(wrap_pyfunction!(hash::generate_hash, m)?)?;
    m.add_function(wrap_pyfunction!(hash::verify_integrity, m)?)?;
    m.add_function(wrap_pyfunction!(hash::get_adler32_shard, m)?)?;
    m.add_function(wrap_pyfunction!(math::calculate_statistical_significance, m)?)?;
    m.add_function(wrap_pyfunction!(math::calculate_jaccard_similarity, m)?)?;
    Ok(())
}
