r"""LLM_CONTEXT_START

## Source: src-old/core/base/execution/agent_delegator.description.md

# Description: src/core/base/execution/agent_delegator.py

Module docstring (if present):

    Delegation management for agent cascading.
    Enables agents to launch sub-tasks by spawning other specialized agents.

Top-level members:
- Classes: AgentDelegator

Notes:
- This description was auto-generated by scripts/generate_docs_for_src.py
## Source: src-old/core/base/execution/agent_delegator.improvements.md

# Improvements: src/core/base/execution/agent_delegator.py

Suggested improvements (automatically generated):
- Add unit tests covering core behavior and edge cases.
- Break large modules into smaller, testable components.
- Avoid heavy imports at module import time; import lazily where appropriate.
- Add type hints and explicit return types for public functions.
- Add logging and better error handling for file and IO operations.
- Consider dependency injection for filesystem and environment interactions.

LLM_CONTEXT_END

"""
