#!/usr/bin/env python3
"""LLM_CONTEXT_START

## Source: src-old/core/base/common/types/typed_prompts.description.md

# Description: src/core/base/common/types/typed_prompts.py

Module docstring (if present):

    TypedPrompts - Type-safe prompt schemas with type guards.

    Inspired by vLLM's inputs.data module for type-safe prompt handling
    with TypedDict schemas and TypeIs type guards.

    Phase 24: Advanced Observability & Parsing

Top-level members:
- Classes: TextPrompt, TokensPrompt, EmbedsPrompt, DataPrompt, ExplicitEncoderDecoderPrompt
- Functions: is_text_prompt, is_tokens_prompt, is_embeds_prompt, is_data_prompt, is_string_prompt, is_explicit_encoder_decoder_prompt, parse_prompt, get_prompt_text, get_prompt_token_ids, has_multi_modal_data

Notes:
- This description was auto-generated by scripts/generate_docs_for_src.py
## Source: src-old/core/base/common/types/typed_prompts.improvements.md

# Improvements: src/core/base/common/types/typed_prompts.py

Suggested improvements (automatically generated):
- Add unit tests covering core behavior and edge cases.
- Break large modules into smaller, testable components.
- Avoid heavy imports at module import time; import lazily where appropriate.
- Add type hints and explicit return types for public functions.
- Add logging and better error handling for file and IO operations.
- Consider dependency injection for filesystem and environment interactions.

LLM_CONTEXT_END

"""
from __future__ import annotations


# Copyright 2026 PyAgent Authors
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
TypedPrompts - Type-safe prompt schemas with type guards.

Inspired by vLLM's inputs.data module for type-safe prompt handling
with TypedDict schemas and TypeIs type guards.

Phase 24: Advanced Observability & Parsing
"""


from typing import Any, Generic, TypeAlias, TypeVar

from typing_extensions import NotRequired, TypedDict, TypeIs

# ============================================================================
# Prompt TypedDicts
# ============================================================================


class TextPrompt(TypedDict):
    """Schema for a text prompt.

    The text will be tokenized before passing to the model.
    """

    prompt: str
    """The input text to be tokenized."""

    multi_modal_data: NotRequired[dict[str, Any] | None]
    """Optional multi-modal data (images, audio, etc.)."""

    mm_processor_kwargs: NotRequired[dict[str, Any] | None]
    """Optional processor kwargs for multi-modal handling."""

    cache_salt: NotRequired[str]
    """Optional cache salt for prefix caching."""


class TokensPrompt(TypedDict):
    """Schema for a pre-tokenized prompt.

    Token IDs are passed directly to the model.
    """

    prompt_token_ids: list[int]
    """List of token IDs to pass to the model."""

    prompt: NotRequired[str]
    """Optional prompt text corresponding to token IDs."""

    token_type_ids: NotRequired[list[int]]
    """Optional token type IDs for cross-encoder models."""

    multi_modal_data: NotRequired[dict[str, Any] | None]
    """Optional multi-modal data."""

    mm_processor_kwargs: NotRequired[dict[str, Any] | None]
    """Optional processor kwargs for multi-modal handling."""

    cache_salt: NotRequired[str]
    """Optional cache salt for prefix caching."""


class EmbedsPrompt(TypedDict):
    """Schema for a prompt provided via embeddings.

    Pre-computed embeddings are passed directly to the model.
    """

    prompt_embeds: Any  # torch.Tensor or numpy array
    """The embeddings of the prompt."""

    cache_salt: NotRequired[str]
    """Optional cache salt for prefix caching."""


class DataPrompt(TypedDict):
    """Schema for generic data prompts.

    Used for custom IO processor plugins.
    """

    data: Any
    """The input data."""

    data_format: str
    """The format of the input data."""


# ============================================================================
# Type aliases
# ============================================================================

SingletonPrompt: TypeAlias = str | TextPrompt | TokensPrompt | EmbedsPrompt
"""
Set of possible schemas for a single prompt:
- A plain text string
- A TextPrompt dict
- A TokensPrompt dict
- An EmbedsPrompt dict
"""

# TypeVar without default for Python 3.12 compatibility
T1 = TypeVar("T1", bound=SingletonPrompt)  # pylint: disable=invalid-name
T2 = TypeVar("T2", bound=SingletonPrompt)  # pylint: disable=invalid-name


class ExplicitEncoderDecoderPrompt(TypedDict, Generic[T1, T2]):
    """Schema for encoder/decoder model prompts.

    Allows specifying separate encoder and decoder prompts.
    """

    encoder_prompt: T1
    """The encoder prompt."""

    decoder_prompt: T2 | None
    """The decoder prompt (optional)."""

    mm_processor_kwargs: NotRequired[dict[str, Any]]
    """Optional processor kwargs (at top level, not in sub-prompts)."""


PromptType: TypeAlias = SingletonPrompt | ExplicitEncoderDecoderPrompt
r"""All possible prompt types including encoder/decoder."""
