"""
LLM_CONTEXT_START

## Source: src-old/core/base/__init__.description.md

# Description: src/core/base/__init__.py

Module docstring (if present):

    Core primitives and base classes for PyAgent.

Top-level members:
- (no top-level classes or functions)

Notes:
- This description was auto-generated by scripts/generate_docs_for_src.py
## Source: src-old/core/base/__init__.improvements.md

# Improvements: src/core/base/__init__.py

Suggested improvements (automatically generated):
- Add unit tests covering core behavior and edge cases.
- Break large modules into smaller, testable components.
- Avoid heavy imports at module import time; import lazily where appropriate.
- Add type hints and explicit return types for public functions.
- Add logging and better error handling for file and IO operations.
- Consider dependency injection for filesystem and environment interactions.

LLM_CONTEXT_END
"""

from __future__ import annotations

# Copyright 2026 PyAgent Authors
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Core primitives and base classes for PyAgent.
"""

import sys

try:
    # Ensure imports using the uppercase module name succeed on case-insensitive
    # filesystems by aliasing the lowercase-loaded module into sys.modules.
    import src.core.base.version as _version_mod

    sys.modules.setdefault(
        "src.core.base.Version", sys.modules.get("src.core.base.version", _version_mod)
    )
except Exception:
    # Best-effort shim; if version can't be imported yet, don't fail package import
    pass

from src.core.base.common.base_interfaces import AgentInterface, OrchestratorInterface
from src.core.base.common.models import AgentConfig, AgentState, PromptTemplate, ResponseQuality
from src.core.base.common.models.core_enums import HealthStatus
from src.core.base.lifecycle.base_agent import BaseAgent
from src.core.base.lifecycle.version import VERSION
from src.core.base.logic.agent_plugin_base import AgentPluginBase

__version__ = VERSION
__all__ = [
    "VERSION",
    "BaseAgent",
    "AgentConfig",
    "AgentState",
    "ResponseQuality",
    "PromptTemplate",
    "AgentInterface",
    "OrchestratorInterface",
    "AgentPluginBase",
    "HealthStatus",
]
