"""
LLM_CONTEXT_START

## Source: src-old/core/base/logic/core/__init__.description.md

# Description: src/core/base/logic/core/__init__.py

Module docstring (if present):

    Core package.

Top-level members:
- (no top-level classes or functions)

Notes:
- This description was auto-generated by scripts/generate_docs_for_src.py
## Source: src-old/core/base/logic/core/__init__.improvements.md

# Improvements: src/core/base/logic/core/__init__.py

Suggested improvements (automatically generated):
- Add unit tests covering core behavior and edge cases.
- Break large modules into smaller, testable components.
- Avoid heavy imports at module import time; import lazily where appropriate.
- Add type hints and explicit return types for public functions.
- Add logging and better error handling for file and IO operations.
- Consider dependency injection for filesystem and environment interactions.

LLM_CONTEXT_END
"""

"""
Core package.
"""

# Copyright 2026 PyAgent Authors
from .events import EventCore  # noqa: F401
from .formatting import FormattingCore  # noqa: F401
from .metrics import MetricsCore  # noqa: F401
from .utils import UtilsCore  # noqa: F401
from .validation import ValidationCore  # noqa: F401
from .code_analyzer import CodeAnalyzerCore  # noqa: F401
from .memory_consolidation_core import MemoryConsolidationCore  # noqa: F401

__all__ = [
    "ValidationCore",
    "MetricsCore",
    "FormattingCore",
    "UtilsCore",
    "EventCore",
    "CodeAnalyzerCore",
    "MemoryConsolidationCore",
]
