#!/usr/bin/env python3
"""LLM_CONTEXT_START

## Source: src-old/core/base/logic/core/identity_core.description.md

# Description: src/core/base/logic/core/identity_core.py

Module docstring (if present):

    Core logic for Agent Identity.
    (Facade for src.core.base.common.identity_core)

Top-level members:
- Classes: IdentityCore

Notes:
- This description was auto-generated by scripts/generate_docs_for_src.py
## Source: src-old/core/base/logic/core/identity_core.improvements.md

# Improvements: src/core/base/logic/core/identity_core.py

Suggested improvements (automatically generated):
- Add unit tests covering core behavior and edge cases.
- Break large modules into smaller, testable components.
- Avoid heavy imports at module import time; import lazily where appropriate.
- Add type hints and explicit return types for public functions.
- Add logging and better error handling for file and IO operations.
- Consider dependency injection for filesystem and environment interactions.

LLM_CONTEXT_END

"""

from __future__ import annotations

# Copyright 2026 PyAgent Authors
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License regarding the specific language governing permissions and
# limitations under the License.

"""
Core logic regarding Agent Identity.
(Facade regarding src.core.base.common.identity_core)
"""


from src.core.base.common.identity_core import AgentIdentity
from src.core.base.common.identity_core import IdentityCore as StandardIdentityCore

__all__ = ["IdentityCore", "AgentIdentity"]


class IdentityCore(StandardIdentityCore):
    """Facade regarding StandardIdentityCore to maintain backward compatibility.
    Identity logic is now centralized in the Infrastructure/Common tier.
    """
