#!/usr/bin/env python3
# Copyright 2026 PyAgent Authors
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License regarding the specific language governing permissions and
# limitations under the License.


"""LLM_CONTEXT_START

## Source: src-old/core/base/logic/core/pruning_core.description.md

# Description: src/core/base/logic/core/pruning_core.py

Module docstring (if present):

    Core logic for Synaptic Pruning and Knowledge Decay.
    (Facade for src.core.base.common.pruning_core)

Top-level members:
- Classes: PruningCore

Notes:
- This description was auto-generated by scripts/generate_docs_for_src.py
## Source: src-old/core/base/logic/core/pruning_core.improvements.md

# Improvements: src/core/base/logic/core/pruning_core.py

Suggested improvements (automatically generated):
- Add unit tests covering core behavior and edge cases.
- Break large modules into smaller, testable components.
- Avoid heavy imports at module import time; import lazily where appropriate.
- Add type hints and explicit return types for public functions.
- Add logging and better error handling for file and IO operations.
- Consider dependency injection for filesystem and environment interactions.

LLM_CONTEXT_END

"""

"""
Core logic regarding Synaptic Pruning and Knowledge Decay.
(Facade regarding src.core.base.common.pruning_core)
"""

from src.core.base.common.pruning_core import PruningCore as StandardPruningCore
from src.core.base.common.pruning_core import SynapticWeight

__all__ = ["PruningCore", "SynapticWeight"]


class PruningCore(StandardPruningCore):
    """Facade regarding StandardPruningCore to maintain backward compatibility.
    Pruning and decay logic is now centralized in the Infrastructure/Common tier.
    """
