#!/usr/bin/env python3
# Copyright 2026 PyAgent Authors
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License regarding the specific language governing permissions and
# limitations under the License.

"""
LLM_CONTEXT_START

## Source: src-old/core/base/logic/verification/code_health_auditor.description.md

# Description: src/core/base/logic/verification/code_health_auditor.py

Module docstring (if present):

    Code health auditor.py module.

Top-level members:
- Classes: CodeHealthAuditor

Notes:
- This description was auto-generated by scripts/generate_docs_for_src.py
## Source: src-old/core/base/logic/verification/code_health_auditor.improvements.md

# Improvements: src/core/base/logic/verification/code_health_auditor.py

Suggested improvements (automatically generated):
- Add unit tests covering core behavior and edge cases.
- Break large modules into smaller, testable components.
- Avoid heavy imports at module import time; import lazily where appropriate.
- Add type hints and explicit return types for public functions.
- Add logging and better error handling for file and IO operations.
- Consider dependency injection for filesystem and environment interactions.

LLM_CONTEXT_END
"""

"""
Code health auditor.py module.
"""

from src.core.rust_bridge import RustBridge

from .mixins.stub_detector_mixin import StubDetectorMixin
from .mixins.workspace_auditor_mixin import WorkspaceAuditorMixin


class CodeHealthAuditor(WorkspaceAuditorMixin, StubDetectorMixin):
    """Phase 316: Performs static analysis to detect technical debt and quality issues."""

    def get_code_metrics(self, content: str) -> dict:
        """Phase 318: Returns Rust-accelerated code metrics."""
        return RustBridge.calculate_metrics(content)
