#!/usr/bin/env python3
# Copyright 2026 PyAgent Authors
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
LLM_CONTEXT_START

## Source: src-old/core/base/logic/structures/__init__.description.md

# Description: src/core/base/logic/structures/__init__.py

Module docstring (if present):

    Base data structures.

    Phase 18-19: Beyond vLLM - Advanced data structures and performance patterns.

Top-level members:
- (no top-level classes or functions)

Notes:
- This description was auto-generated by scripts/generate_docs_for_src.py
## Source: src-old/core/base/logic/structures/__init__.improvements.md

# Improvements: src/core/base/logic/structures/__init__.py

Suggested improvements (automatically generated):
- Add unit tests covering core behavior and edge cases.
- Break large modules into smaller, testable components.
- Avoid heavy imports at module import time; import lazily where appropriate.
- Add type hints and explicit return types for public functions.
- Add logging and better error handling for file and IO operations.
- Consider dependency injection for filesystem and environment interactions.

LLM_CONTEXT_END
"""

"""
Base data structures.

Phase 18-19: Beyond vLLM - Advanced data structures and performance patterns.
"""

from src.core.base.logic.structures.bloom_filter import (
    BloomFilter,
    CountingBloomFilter,
    ScalableBloomFilter,
)
from src.core.base.logic.structures.lock_free_queue import (
    BatchingQueue,
    MPMCQueue,
    PriorityQueue,
    QueueStats,
    SPSCQueue,
    WorkStealingDeque,
)
from src.core.base.logic.structures.memory_arena import (ArenaStats,
                                                         MemoryArena,
                                                         SlabAllocator,
                                                         StackArena,
                                                         TypedArena,
                                                         temp_arena,
                                                         thread_temp_alloc)
from src.core.base.logic.structures.object_pool import (BufferPool, ObjectPool,
                                                        PoolStats,
                                                        TieredBufferPool,
                                                        TypedObjectPool,
                                                        pooled_dict,
                                                        pooled_list,
                                                        pooled_set)
from src.core.base.logic.structures.ring_buffer import (
    RingBuffer, SlidingWindowAggregator, ThreadSafeRingBuffer,
    TimeSeriesBuffer, TimestampedValue)

__all__ = [
    # Bloom Filters (Phase 18)
    "BloomFilter",
    "CountingBloomFilter",
    "ScalableBloomFilter",
    # Ring Buffers (Phase 18)
    "RingBuffer",
    "ThreadSafeRingBuffer",
    "TimeSeriesBuffer",
    "TimestampedValue",
    "SlidingWindowAggregator",
    # Object Pools (Phase 19)
    "ObjectPool",
    "TypedObjectPool",
    "BufferPool",
    "TieredBufferPool",
    "PoolStats",
    "pooled_list",
    "pooled_dict",
    "pooled_set",
    # Queues (Phase 19)
    "MPMCQueue",
    "SPSCQueue",
    "PriorityQueue",
    "WorkStealingDeque",
    "BatchingQueue",
    "QueueStats",
    # Memory Arenas (Phase 19)
    "MemoryArena",
    "TypedArena",
    "StackArena",
    "SlabAllocator",
    "ArenaStats",
    "temp_arena",
    "thread_temp_alloc",
]
