#!/usr/bin/env python3
# Copyright 2026 PyAgent Authors
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import argparse
import difflib
import sys
from pathlib import Path

from .logger import AutoFixLogger
from .rule_engine import RuleEngine
from .transaction import TransactionManager


def main() -> None:
    parser = argparse.ArgumentParser(description="Run auto-fix rules")
    parser.add_argument("--rules", help="directory containing rule definitions")
    parser.add_argument(
        "--dry-run", action="store_true", help="show proposed fixes only"
    )
    parser.add_argument("--apply", action="store_true", help="apply fixes to files")
    parser.add_argument("--verbose", action="store_true")
    args = parser.parse_args()

    if not args.dry_run and not args.apply:
        parser.error("must specify either --dry-run or --apply")

    engine = RuleEngine.load_from_dir(args.rules)
    txn = TransactionManager()
    logger = AutoFixLogger()

    # placeholder: iterate over files and evaluate rules
    for path in Path(".").rglob("*.py"):
        try:
            content = path.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            # some files (e.g. generated bytecode or non-text) may not be
            # valid UTF-8; ignore those and move on.
            continue
        fixes = engine.evaluate(str(path), content)
        for fix in fixes:
            # compute unified diff between original and replacement

            original_lines = content.splitlines(keepends=True)
            replacement_lines = fix.replacement.splitlines(keepends=True)
            diff_lines = list(
                difflib.unified_diff(
                    original_lines,
                    replacement_lines,
                    fromfile=str(path),
                    tofile=f"{path} (fixed)",
                )
            )
            diff = "".join(diff_lines)

            from .logger import PlannedChange

            logger.record(
                PlannedChange(path=str(path), description=fix.description, diff=diff)
            )
            if args.apply and not args.dry_run:
                with txn.transaction(f"auto fix {fix.description}"):
                    path.write_text(fix.replacement, encoding="utf-8")

    if args.dry_run:
        sys.stdout.write(logger.report())


if __name__ == "__main__":
    main()
