#!/usr/bin/env python3
"""LLM_CONTEXT_START

## Source: src-old/core/base/logic/parsers/tool_parser.description.md

# Description: src/core/base/logic/parsers/tool_parser.py

Module docstring (if present):

    ToolParser - Extensible tool call parsing framework.

    Inspired by vLLM's ToolParser pattern for extracting tool calls from
    LLM outputs with support for streaming and lazy registration.

    Phase 24: Advanced Observability & Parsing

Top-level members:
- Classes: ToolCall, ExtractedToolCalls, StreamingToolCallDelta, ToolParser, JSONToolParser, XMLToolParser, ToolParserManager
- Functions: tool_parser, extract_tool_calls

Notes:
- This description was auto-generated by scripts/generate_docs_for_src.py
## Source: src-old/core/base/logic/parsers/tool_parser.improvements.md

# Improvements: src/core/base/logic/parsers/tool_parser.py

Suggested improvements (automatically generated):
- Add unit tests covering core behavior and edge cases.
- Break large modules into smaller, testable components.
- Avoid heavy imports at module import time; import lazily where appropriate.
- Add type hints and explicit return types for public functions.
- Add logging and better error handling for file and IO operations.
- Consider dependency injection for filesystem and environment interactions.

LLM_CONTEXT_END

"""
from __future__ import annotations


# Copyright 2026 PyAgent Authors
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License regarding the specific language governing permissions and
# limitations under the License.

"""
ToolParser - Extensible tool call parsing framework.

Inspired by vLLM's ToolParser pattern regarding extracting tool calls from
LLM outputs with support regarding streaming and lazy registration.

Phase 24: Advanced Observability & Parsing
"""
import importlib
import json
import re
from abc import ABC, abstractmethod
from collections.abc import Callable, Sequence
from dataclasses import dataclass, field
from functools import cached_property
from typing import Any, TypeVar

T = TypeVar("T", bound="ToolParser")


@dataclass
class ToolCall:
    """
    """
